// Code generated by wsdl2go. DO NOT EDIT.

package imuis

import (
	"github.com/omniboost/go-imuis/wsdl2go/soap"
)

// Namespace was auto-generated from WSDL.
var Namespace = "https://cloudswitch.imuisonline.com/"

// NewWs1_xmlSoap creates an initializes a Ws1_xmlSoap.
func NewWs1_xmlSoap(cli *soap.Client) Ws1_xmlSoap {
	return &ws1_xmlSoap{cli}
}

// Ws1_xmlSoap was auto-generated from WSDL
// and defines interface for the remote service. Useful for testing.
type Ws1_xmlSoap interface {
	// CheckConnection was auto-generated from WSDL.
	CheckConnection(CheckConnection *CheckConnection) (*CheckConnectionResponse, error)

	// CreateGoederenontvangst was auto-generated from WSDL.
	CreateGoederenontvangst(CreateGoederenontvangst *CreateGoederenontvangst) (*CreateGoederenontvangstResponse, error)

	// CreateInkoopOrder was auto-generated from WSDL.
	CreateInkoopOrder(CreateInkoopOrder *CreateInkoopOrder) (*CreateInkoopOrderResponse, error)

	// CreateInkoopfactuur was auto-generated from WSDL.
	CreateInkoopfactuur(CreateInkoopfactuur *CreateInkoopfactuur) (*CreateInkoopfactuurResponse, error)

	// CreateInkooporderRegel was auto-generated from WSDL.
	CreateInkooporderRegel(CreateInkooporderRegel *CreateInkooporderRegel) (*CreateInkooporderRegelResponse, error)

	// CreateJournaalpost was auto-generated from WSDL.
	CreateJournaalpost(CreateJournaalpost *CreateJournaalpost) (*CreateJournaalpostResponse, error)

	// CreateSpitsfactuur was auto-generated from WSDL.
	CreateSpitsfactuur(CreateSpitsfactuur *CreateSpitsfactuur) (*CreateSpitsfactuurResponse, error)

	// CreateStamTabelRecord was auto-generated from WSDL.
	CreateStamTabelRecord(CreateStamTabelRecord *CreateStamTabelRecord) (*CreateStamTabelRecordResponse, error)

	// CreateVerkoopContract was auto-generated from WSDL.
	CreateVerkoopContract(CreateVerkoopContract *CreateVerkoopContract) (*CreateVerkoopContractResponse, error)

	// CreateVerkoopContractRegel was auto-generated from WSDL.
	CreateVerkoopContractRegel(CreateVerkoopContractRegel *CreateVerkoopContractRegel) (*CreateVerkoopContractRegelResponse, error)

	// CreateVerkoopOrder was auto-generated from WSDL.
	CreateVerkoopOrder(CreateVerkoopOrder *CreateVerkoopOrder) (*CreateVerkoopOrderResponse, error)

	// CreateVerkooporderPickbon was auto-generated from WSDL.
	CreateVerkooporderPickbon(CreateVerkooporderPickbon *CreateVerkooporderPickbon) (*CreateVerkooporderPickbonResponse, error)

	// CreateVerkooporderRegel was auto-generated from WSDL.
	CreateVerkooporderRegel(CreateVerkooporderRegel *CreateVerkooporderRegel) (*CreateVerkooporderRegelResponse, error)

	// DeleteInkooporder was auto-generated from WSDL.
	DeleteInkooporder(DeleteInkooporder *DeleteInkooporder) (*DeleteInkooporderResponse, error)

	// DeleteInkooporderRegel was auto-generated from WSDL.
	DeleteInkooporderRegel(DeleteInkooporderRegel *DeleteInkooporderRegel) (*DeleteInkooporderRegelResponse, error)

	// DeleteJournaalpost was auto-generated from WSDL.
	DeleteJournaalpost(DeleteJournaalpost *DeleteJournaalpost) (*DeleteJournaalpostResponse, error)

	// DeleteStamtabelRecord was auto-generated from WSDL.
	DeleteStamtabelRecord(DeleteStamtabelRecord *DeleteStamtabelRecord) (*DeleteStamtabelRecordResponse, error)

	// DeleteVerkoopContract was auto-generated from WSDL.
	DeleteVerkoopContract(DeleteVerkoopContract *DeleteVerkoopContract) (*DeleteVerkoopContractResponse, error)

	// DeleteVerkoopContractRegel was auto-generated from WSDL.
	DeleteVerkoopContractRegel(DeleteVerkoopContractRegel *DeleteVerkoopContractRegel) (*DeleteVerkoopContractRegelResponse, error)

	// DeleteVerkooporder was auto-generated from WSDL.
	DeleteVerkooporder(DeleteVerkooporder *DeleteVerkooporder) (*DeleteVerkooporderResponse, error)

	// DeleteVerkooporderRegel was auto-generated from WSDL.
	DeleteVerkooporderRegel(DeleteVerkooporderRegel *DeleteVerkooporderRegel) (*DeleteVerkooporderRegelResponse, error)

	// GetAdmInfo was auto-generated from WSDL.
	GetAdmInfo(GetAdmInfo *GetAdmInfo) (*GetAdmInfoResponse, error)

	// GetLaatsteBoekingPeriode was auto-generated from WSDL.
	GetLaatsteBoekingPeriode(GetLaatsteBoekingPeriode *GetLaatsteBoekingPeriode) (*GetLaatsteBoekingPeriodeResponse, error)

	// GetPredefindQuery was auto-generated from WSDL.
	GetPredefindQuery(GetPredefindQuery *GetPredefindQuery) (*GetPredefindQueryResponse, error)

	// GetStamtabelRecords was auto-generated from WSDL.
	GetStamtabelRecords(GetStamtabelRecords *GetStamtabelRecords, records interface{}) (*GetStamtabelRecordsResponse, error)

	// GetTimeStamp was auto-generated from WSDL.
	GetTimeStamp(GetTimeStamp *GetTimeStamp) (*GetTimeStampResponse, error)

	// GetiMUISVersion was auto-generated from WSDL.
	GetiMUISVersion(GetiMUISVersion *GetiMUISVersion) (*GetiMUISVersionResponse, error)

	// KeepSession was auto-generated from WSDL.
	KeepSession(KeepSession *KeepSession) (*KeepSessionResponse, error)

	// Login was auto-generated from WSDL.
	Login(Login *Login) (*LoginResponse, error)

	// Logout was auto-generated from WSDL.
	Logout(Logout *Logout) (*LogoutResponse, error)

	// UpdateInkooporderRegel was auto-generated from WSDL.
	UpdateInkooporderRegel(UpdateInkooporderRegel *UpdateInkooporderRegel) (*UpdateInkooporderRegelResponse, error)

	// UpdateJournaalpost was auto-generated from WSDL.
	UpdateJournaalpost(UpdateJournaalpost *UpdateJournaalpost) (*UpdateJournaalpostResponse, error)

	// UpdateStamtabelRecord was auto-generated from WSDL.
	UpdateStamtabelRecord(UpdateStamtabelRecord *UpdateStamtabelRecord) (*UpdateStamtabelRecordResponse, error)

	// UpdateVerkoopContractRegel was auto-generated from WSDL.
	UpdateVerkoopContractRegel(UpdateVerkoopContractRegel *UpdateVerkoopContractRegel) (*UpdateVerkoopContractRegelResponse, error)

	// UpdateVerkooporderPickBonGepakt was auto-generated from WSDL.
	UpdateVerkooporderPickBonGepakt(UpdateVerkooporderPickBonGepakt *UpdateVerkooporderPickBonGepakt) (*UpdateVerkooporderPickBonGepaktResponse, error)

	// UpdateVerkooporderPickbonGereed was auto-generated from WSDL.
	UpdateVerkooporderPickbonGereed(UpdateVerkooporderPickbonGereed *UpdateVerkooporderPickbonGereed) (*UpdateVerkooporderPickbonGereedResponse, error)

	// UpdateVerkooporderRegel was auto-generated from WSDL.
	UpdateVerkooporderRegel(UpdateVerkooporderRegel *UpdateVerkooporderRegel) (*UpdateVerkooporderRegelResponse, error)
}

// ArrayOfString was auto-generated from WSDL.
type ArrayOfString struct {
	String []*string `xml:"string,omitempty" json:"string,omitempty" yaml:"string,omitempty"`
}

// CheckConnection was auto-generated from WSDL.
type CheckConnection struct {
}

// CheckConnectionResponse was auto-generated from WSDL.
type CheckConnectionResponse struct {
	CheckConnectionResult bool `xml:"CheckConnectionResult" json:"CheckConnectionResult" yaml:"CheckConnectionResult"`
}

// CreateGoederenontvangst was auto-generated from WSDL.
type CreateGoederenontvangst struct {
	PartnerKey        *string `xml:"PartnerKey,omitempty" json:"PartnerKey,omitempty" yaml:"PartnerKey,omitempty"`
	Omgevingscode     *string `xml:"Omgevingscode,omitempty" json:"Omgevingscode,omitempty" yaml:"Omgevingscode,omitempty"`
	SessionId         *string `xml:"SessionId,omitempty" json:"SessionId,omitempty" yaml:"SessionId,omitempty"`
	Goederenontvangst *string `xml:"Goederenontvangst,omitempty" json:"Goederenontvangst,omitempty" yaml:"Goederenontvangst,omitempty"`
	ONTVANGSTNR       int     `xml:"ONTVANGSTNR" json:"ONTVANGSTNR" yaml:"ONTVANGSTNR"`
	Foutmelding       *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// CreateGoederenontvangstResponse was auto-generated from WSDL.
type CreateGoederenontvangstResponse struct {
	CreateGoederenontvangstResult bool    `xml:"CreateGoederenontvangstResult" json:"CreateGoederenontvangstResult" yaml:"CreateGoederenontvangstResult"`
	Goederenontvangst             *string `xml:"Goederenontvangst,omitempty" json:"Goederenontvangst,omitempty" yaml:"Goederenontvangst,omitempty"`
	ONTVANGSTNR                   int     `xml:"ONTVANGSTNR" json:"ONTVANGSTNR" yaml:"ONTVANGSTNR"`
	Foutmelding                   *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// CreateInkoopOrder was auto-generated from WSDL.
type CreateInkoopOrder struct {
	PartnerKey    *string `xml:"PartnerKey,omitempty" json:"PartnerKey,omitempty" yaml:"PartnerKey,omitempty"`
	Omgevingscode *string `xml:"Omgevingscode,omitempty" json:"Omgevingscode,omitempty" yaml:"Omgevingscode,omitempty"`
	SessionId     *string `xml:"SessionId,omitempty" json:"SessionId,omitempty" yaml:"SessionId,omitempty"`
	Inkooporder   *string `xml:"Inkooporder,omitempty" json:"Inkooporder,omitempty" yaml:"Inkooporder,omitempty"`
	ORDNR         int     `xml:"ORDNR" json:"ORDNR" yaml:"ORDNR"`
	Foutmelding   *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// CreateInkoopOrderResponse was auto-generated from WSDL.
type CreateInkoopOrderResponse struct {
	CreateInkoopOrderResult bool    `xml:"CreateInkoopOrderResult" json:"CreateInkoopOrderResult" yaml:"CreateInkoopOrderResult"`
	Inkooporder             *string `xml:"Inkooporder,omitempty" json:"Inkooporder,omitempty" yaml:"Inkooporder,omitempty"`
	ORDNR                   int     `xml:"ORDNR" json:"ORDNR" yaml:"ORDNR"`
	Foutmelding             *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// CreateInkoopfactuur was auto-generated from WSDL.
type CreateInkoopfactuur struct {
	PartnerKey    *string `xml:"PartnerKey,omitempty" json:"PartnerKey,omitempty" yaml:"PartnerKey,omitempty"`
	Omgevingscode *string `xml:"Omgevingscode,omitempty" json:"Omgevingscode,omitempty" yaml:"Omgevingscode,omitempty"`
	SessionId     *string `xml:"SessionId,omitempty" json:"SessionId,omitempty" yaml:"SessionId,omitempty"`
	Inkoopfactuur *string `xml:"Inkoopfactuur,omitempty" json:"Inkoopfactuur,omitempty" yaml:"Inkoopfactuur,omitempty"`
	INKFACTNR     *string `xml:"INKFACTNR,omitempty" json:"INKFACTNR,omitempty" yaml:"INKFACTNR,omitempty"`
	Foutmelding   *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// CreateInkoopfactuurResponse was auto-generated from WSDL.
type CreateInkoopfactuurResponse struct {
	CreateInkoopfactuurResult bool    `xml:"CreateInkoopfactuurResult" json:"CreateInkoopfactuurResult" yaml:"CreateInkoopfactuurResult"`
	Inkoopfactuur             *string `xml:"Inkoopfactuur,omitempty" json:"Inkoopfactuur,omitempty" yaml:"Inkoopfactuur,omitempty"`
	INKFACTNR                 *string `xml:"INKFACTNR,omitempty" json:"INKFACTNR,omitempty" yaml:"INKFACTNR,omitempty"`
	Foutmelding               *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// CreateInkooporderRegel was auto-generated from WSDL.
type CreateInkooporderRegel struct {
	PartnerKey    *string `xml:"PartnerKey,omitempty" json:"PartnerKey,omitempty" yaml:"PartnerKey,omitempty"`
	Omgevingscode *string `xml:"Omgevingscode,omitempty" json:"Omgevingscode,omitempty" yaml:"Omgevingscode,omitempty"`
	SessionId     *string `xml:"SessionId,omitempty" json:"SessionId,omitempty" yaml:"SessionId,omitempty"`
	Inkooporder   *string `xml:"Inkooporder,omitempty" json:"Inkooporder,omitempty" yaml:"Inkooporder,omitempty"`
	ORDNR         int     `xml:"ORDNR" json:"ORDNR" yaml:"ORDNR"`
	Foutmelding   *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// CreateInkooporderRegelResponse was auto-generated from WSDL.
type CreateInkooporderRegelResponse struct {
	CreateInkooporderRegelResult bool    `xml:"CreateInkooporderRegelResult" json:"CreateInkooporderRegelResult" yaml:"CreateInkooporderRegelResult"`
	Inkooporder                  *string `xml:"Inkooporder,omitempty" json:"Inkooporder,omitempty" yaml:"Inkooporder,omitempty"`
	ORDNR                        int     `xml:"ORDNR" json:"ORDNR" yaml:"ORDNR"`
	Foutmelding                  *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// CreateJournaalpost was auto-generated from WSDL.
type CreateJournaalpost struct {
	PartnerKey    *string        `xml:"PartnerKey,omitempty" json:"PartnerKey,omitempty" yaml:"PartnerKey,omitempty"`
	Omgevingscode *string        `xml:"Omgevingscode,omitempty" json:"Omgevingscode,omitempty" yaml:"Omgevingscode,omitempty"`
	SessionId     *string        `xml:"SessionId,omitempty" json:"SessionId,omitempty" yaml:"SessionId,omitempty"`
	Journaalpost  *Journaalpost  `xml:"Journaalpost,omitempty" json:"Journaalpost,omitempty" yaml:"Journaalpost,omitempty"`
	Primarykey    *ArrayOfString `xml:"Primarykey,omitempty" json:"Primarykey,omitempty" yaml:"Primarykey,omitempty"`
	Foutmelding   *string        `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// CreateJournaalpostResponse was auto-generated from WSDL.
type CreateJournaalpostResponse struct {
	CreateJournaalpostResult bool                                   `xml:"CreateJournaalpostResult" json:"CreateJournaalpostResult" yaml:"CreateJournaalpostResult"`
	Journaalpost             CreateJournaalpostResponseJournaalpost `xml:"Journaalpost,omitempty" json:"Journaalpost,omitempty" yaml:"Journaalpost,omitempty"`
	Primarykey               *ArrayOfString                         `xml:"Primarykey,omitempty" json:"Primarykey,omitempty" yaml:"Primarykey,omitempty"`
	Foutmelding              *string                                `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// CreateSpitsfactuur was auto-generated from WSDL.
type CreateSpitsfactuur struct {
	PartnerKey       *string `xml:"PartnerKey,omitempty" json:"PartnerKey,omitempty" yaml:"PartnerKey,omitempty"`
	Omgevingscode    *string `xml:"Omgevingscode,omitempty" json:"Omgevingscode,omitempty" yaml:"Omgevingscode,omitempty"`
	SessionId        *string `xml:"SessionId,omitempty" json:"SessionId,omitempty" yaml:"SessionId,omitempty"`
	SessionIdMWsys   *string `xml:"SessionIdMWsys,omitempty" json:"SessionIdMWsys,omitempty" yaml:"SessionIdMWsys,omitempty"`
	Username         *string `xml:"Username,omitempty" json:"Username,omitempty" yaml:"Username,omitempty"`
	Password         *string `xml:"Password,omitempty" json:"Password,omitempty" yaml:"Password,omitempty"`
	Verkooporder     *string `xml:"Verkooporder,omitempty" json:"Verkooporder,omitempty" yaml:"Verkooporder,omitempty"`
	ORDNR            int     `xml:"ORDNR" json:"ORDNR" yaml:"ORDNR"`
	SaveOrderMelding *string `xml:"SaveOrderMelding,omitempty" json:"SaveOrderMelding,omitempty" yaml:"SaveOrderMelding,omitempty"`
	Foutmelding      *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// CreateSpitsfactuurResponse was auto-generated from WSDL.
type CreateSpitsfactuurResponse struct {
	CreateSpitsfactuurResult bool    `xml:"CreateSpitsfactuurResult" json:"CreateSpitsfactuurResult" yaml:"CreateSpitsfactuurResult"`
	Verkooporder             *string `xml:"Verkooporder,omitempty" json:"Verkooporder,omitempty" yaml:"Verkooporder,omitempty"`
	ORDNR                    int     `xml:"ORDNR" json:"ORDNR" yaml:"ORDNR"`
	SaveOrderMelding         *string `xml:"SaveOrderMelding,omitempty" json:"SaveOrderMelding,omitempty" yaml:"SaveOrderMelding,omitempty"`
	Foutmelding              *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// CreateStamTabelRecord was auto-generated from WSDL.
type CreateStamTabelRecord struct {
	PartnerKey    *string                         `xml:"PartnerKey,omitempty" json:"PartnerKey,omitempty" yaml:"PartnerKey,omitempty"`
	Omgevingscode *string                         `xml:"Omgevingscode,omitempty" json:"Omgevingscode,omitempty" yaml:"Omgevingscode,omitempty"`
	SessionId     *string                         `xml:"SessionId,omitempty" json:"SessionId,omitempty" yaml:"SessionId,omitempty"`
	Stamtabel     *CreateStamTabelRecordStamtabel `xml:"Stamtabel,omitempty" json:"Stamtabel,omitempty" yaml:"Stamtabel,omitempty"`
	Primarykey    *string                         `xml:"Primarykey,omitempty" json:"Primarykey,omitempty" yaml:"Primarykey,omitempty"`
	Foutmelding   *string                         `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// CreateStamTabelRecordResponse was auto-generated from WSDL.
type CreateStamTabelRecordResponse struct {
	CreateStamTabelRecordResult bool    `xml:"CreateStamTabelRecordResult" json:"CreateStamTabelRecordResult" yaml:"CreateStamTabelRecordResult"`
	Primarykey                  *string `xml:"Primarykey,omitempty" json:"Primarykey,omitempty" yaml:"Primarykey,omitempty"`
	Foutmelding                 *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// CreateVerkoopContract was auto-generated from WSDL.
type CreateVerkoopContract struct {
	PartnerKey    *string `xml:"PartnerKey,omitempty" json:"PartnerKey,omitempty" yaml:"PartnerKey,omitempty"`
	Omgevingscode *string `xml:"Omgevingscode,omitempty" json:"Omgevingscode,omitempty" yaml:"Omgevingscode,omitempty"`
	SessionId     *string `xml:"SessionId,omitempty" json:"SessionId,omitempty" yaml:"SessionId,omitempty"`
	Contract      *string `xml:"Contract,omitempty" json:"Contract,omitempty" yaml:"Contract,omitempty"`
	ONDERHCTR     *string `xml:"ONDERHCTR,omitempty" json:"ONDERHCTR,omitempty" yaml:"ONDERHCTR,omitempty"`
	Foutmelding   *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// CreateVerkoopContractRegel was auto-generated from WSDL.
type CreateVerkoopContractRegel struct {
	PartnerKey    *string `xml:"PartnerKey,omitempty" json:"PartnerKey,omitempty" yaml:"PartnerKey,omitempty"`
	Omgevingscode *string `xml:"Omgevingscode,omitempty" json:"Omgevingscode,omitempty" yaml:"Omgevingscode,omitempty"`
	SessionId     *string `xml:"SessionId,omitempty" json:"SessionId,omitempty" yaml:"SessionId,omitempty"`
	Contract      *string `xml:"Contract,omitempty" json:"Contract,omitempty" yaml:"Contract,omitempty"`
	ONDERHCTR     int     `xml:"ONDERHCTR" json:"ONDERHCTR" yaml:"ONDERHCTR"`
	Foutmelding   *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// CreateVerkoopContractRegelResponse was auto-generated from WSDL.
type CreateVerkoopContractRegelResponse struct {
	CreateVerkoopContractRegelResult bool    `xml:"CreateVerkoopContractRegelResult" json:"CreateVerkoopContractRegelResult" yaml:"CreateVerkoopContractRegelResult"`
	Contract                         *string `xml:"Contract,omitempty" json:"Contract,omitempty" yaml:"Contract,omitempty"`
	ONDERHCTR                        int     `xml:"ONDERHCTR" json:"ONDERHCTR" yaml:"ONDERHCTR"`
	Foutmelding                      *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// CreateVerkoopContractResponse was auto-generated from WSDL.
type CreateVerkoopContractResponse struct {
	CreateVerkoopContractResult bool    `xml:"CreateVerkoopContractResult" json:"CreateVerkoopContractResult" yaml:"CreateVerkoopContractResult"`
	Contract                    *string `xml:"Contract,omitempty" json:"Contract,omitempty" yaml:"Contract,omitempty"`
	ONDERHCTR                   *string `xml:"ONDERHCTR,omitempty" json:"ONDERHCTR,omitempty" yaml:"ONDERHCTR,omitempty"`
	Foutmelding                 *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// CreateVerkoopOrder was auto-generated from WSDL.
type CreateVerkoopOrder struct {
	PartnerKey    *string `xml:"PartnerKey,omitempty" json:"PartnerKey,omitempty" yaml:"PartnerKey,omitempty"`
	Omgevingscode *string `xml:"Omgevingscode,omitempty" json:"Omgevingscode,omitempty" yaml:"Omgevingscode,omitempty"`
	SessionId     *string `xml:"SessionId,omitempty" json:"SessionId,omitempty" yaml:"SessionId,omitempty"`
	Verkooporder  *string `xml:"Verkooporder,omitempty" json:"Verkooporder,omitempty" yaml:"Verkooporder,omitempty"`
	ORDNR         int     `xml:"ORDNR" json:"ORDNR" yaml:"ORDNR"`
	Foutmelding   *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// CreateVerkoopOrderResponse was auto-generated from WSDL.
type CreateVerkoopOrderResponse struct {
	CreateVerkoopOrderResult bool    `xml:"CreateVerkoopOrderResult" json:"CreateVerkoopOrderResult" yaml:"CreateVerkoopOrderResult"`
	Verkooporder             *string `xml:"Verkooporder,omitempty" json:"Verkooporder,omitempty" yaml:"Verkooporder,omitempty"`
	ORDNR                    int     `xml:"ORDNR" json:"ORDNR" yaml:"ORDNR"`
	Foutmelding              *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// CreateVerkooporderPickbon was auto-generated from WSDL.
type CreateVerkooporderPickbon struct {
	PartnerKey    *string `xml:"PartnerKey,omitempty" json:"PartnerKey,omitempty" yaml:"PartnerKey,omitempty"`
	Omgevingscode *string `xml:"Omgevingscode,omitempty" json:"Omgevingscode,omitempty" yaml:"Omgevingscode,omitempty"`
	SessionId     *string `xml:"SessionId,omitempty" json:"SessionId,omitempty" yaml:"SessionId,omitempty"`
	Selectie      *string `xml:"Selectie,omitempty" json:"Selectie,omitempty" yaml:"Selectie,omitempty"`
	Foutmelding   *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// CreateVerkooporderPickbonResponse was auto-generated from WSDL.
type CreateVerkooporderPickbonResponse struct {
	CreateVerkooporderPickbonResult bool    `xml:"CreateVerkooporderPickbonResult" json:"CreateVerkooporderPickbonResult" yaml:"CreateVerkooporderPickbonResult"`
	Foutmelding                     *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// CreateVerkooporderRegel was auto-generated from WSDL.
type CreateVerkooporderRegel struct {
	PartnerKey    *string `xml:"PartnerKey,omitempty" json:"PartnerKey,omitempty" yaml:"PartnerKey,omitempty"`
	Omgevingscode *string `xml:"Omgevingscode,omitempty" json:"Omgevingscode,omitempty" yaml:"Omgevingscode,omitempty"`
	SessionId     *string `xml:"SessionId,omitempty" json:"SessionId,omitempty" yaml:"SessionId,omitempty"`
	Verkooporder  *string `xml:"Verkooporder,omitempty" json:"Verkooporder,omitempty" yaml:"Verkooporder,omitempty"`
	ORDNR         int     `xml:"ORDNR" json:"ORDNR" yaml:"ORDNR"`
	Foutmelding   *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// CreateVerkooporderRegelResponse was auto-generated from WSDL.
type CreateVerkooporderRegelResponse struct {
	CreateVerkooporderRegelResult bool    `xml:"CreateVerkooporderRegelResult" json:"CreateVerkooporderRegelResult" yaml:"CreateVerkooporderRegelResult"`
	Verkooporder                  *string `xml:"Verkooporder,omitempty" json:"Verkooporder,omitempty" yaml:"Verkooporder,omitempty"`
	ORDNR                         int     `xml:"ORDNR" json:"ORDNR" yaml:"ORDNR"`
	Foutmelding                   *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// DeleteInkooporder was auto-generated from WSDL.
type DeleteInkooporder struct {
	PartnerKey    *string `xml:"PartnerKey,omitempty" json:"PartnerKey,omitempty" yaml:"PartnerKey,omitempty"`
	Omgevingscode *string `xml:"Omgevingscode,omitempty" json:"Omgevingscode,omitempty" yaml:"Omgevingscode,omitempty"`
	SessionId     *string `xml:"SessionId,omitempty" json:"SessionId,omitempty" yaml:"SessionId,omitempty"`
	Mutatie       *string `xml:"Mutatie,omitempty" json:"Mutatie,omitempty" yaml:"Mutatie,omitempty"`
	Foutmelding   *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// DeleteInkooporderRegel was auto-generated from WSDL.
type DeleteInkooporderRegel struct {
	PartnerKey    *string `xml:"PartnerKey,omitempty" json:"PartnerKey,omitempty" yaml:"PartnerKey,omitempty"`
	Omgevingscode *string `xml:"Omgevingscode,omitempty" json:"Omgevingscode,omitempty" yaml:"Omgevingscode,omitempty"`
	SessionId     *string `xml:"SessionId,omitempty" json:"SessionId,omitempty" yaml:"SessionId,omitempty"`
	Mutatie       *string `xml:"Mutatie,omitempty" json:"Mutatie,omitempty" yaml:"Mutatie,omitempty"`
	Foutmelding   *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// DeleteInkooporderRegelResponse was auto-generated from WSDL.
type DeleteInkooporderRegelResponse struct {
	DeleteInkooporderRegelResult bool    `xml:"DeleteInkooporderRegelResult" json:"DeleteInkooporderRegelResult" yaml:"DeleteInkooporderRegelResult"`
	Foutmelding                  *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// DeleteInkooporderResponse was auto-generated from WSDL.
type DeleteInkooporderResponse struct {
	DeleteInkooporderResult bool    `xml:"DeleteInkooporderResult" json:"DeleteInkooporderResult" yaml:"DeleteInkooporderResult"`
	Foutmelding             *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// DeleteJournaalpost was auto-generated from WSDL.
type DeleteJournaalpost struct {
	PartnerKey    *string `xml:"PartnerKey,omitempty" json:"PartnerKey,omitempty" yaml:"PartnerKey,omitempty"`
	Omgevingscode *string `xml:"Omgevingscode,omitempty" json:"Omgevingscode,omitempty" yaml:"Omgevingscode,omitempty"`
	SessionId     *string `xml:"SessionId,omitempty" json:"SessionId,omitempty" yaml:"SessionId,omitempty"`
	Primarykey    *string `xml:"Primarykey,omitempty" json:"Primarykey,omitempty" yaml:"Primarykey,omitempty"`
	Foutmelding   *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// DeleteJournaalpostResponse was auto-generated from WSDL.
type DeleteJournaalpostResponse struct {
	DeleteJournaalpostResult bool    `xml:"DeleteJournaalpostResult" json:"DeleteJournaalpostResult" yaml:"DeleteJournaalpostResult"`
	Foutmelding              *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// DeleteStamtabelRecord was auto-generated from WSDL.
type DeleteStamtabelRecord struct {
	PartnerKey    *string `xml:"PartnerKey,omitempty" json:"PartnerKey,omitempty" yaml:"PartnerKey,omitempty"`
	Omgevingscode *string `xml:"Omgevingscode,omitempty" json:"Omgevingscode,omitempty" yaml:"Omgevingscode,omitempty"`
	SessionId     *string `xml:"SessionId,omitempty" json:"SessionId,omitempty" yaml:"SessionId,omitempty"`
	Mutatie       *string `xml:"Mutatie,omitempty" json:"Mutatie,omitempty" yaml:"Mutatie,omitempty"`
	Foutmelding   *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// DeleteStamtabelRecordResponse was auto-generated from WSDL.
type DeleteStamtabelRecordResponse struct {
	DeleteStamtabelRecordResult bool    `xml:"DeleteStamtabelRecordResult" json:"DeleteStamtabelRecordResult" yaml:"DeleteStamtabelRecordResult"`
	Foutmelding                 *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// DeleteVerkoopContract was auto-generated from WSDL.
type DeleteVerkoopContract struct {
	PartnerKey    *string `xml:"PartnerKey,omitempty" json:"PartnerKey,omitempty" yaml:"PartnerKey,omitempty"`
	Omgevingscode *string `xml:"Omgevingscode,omitempty" json:"Omgevingscode,omitempty" yaml:"Omgevingscode,omitempty"`
	SessionId     *string `xml:"SessionId,omitempty" json:"SessionId,omitempty" yaml:"SessionId,omitempty"`
	Mutatie       *string `xml:"Mutatie,omitempty" json:"Mutatie,omitempty" yaml:"Mutatie,omitempty"`
	Foutmelding   *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// DeleteVerkoopContractRegel was auto-generated from WSDL.
type DeleteVerkoopContractRegel struct {
	PartnerKey    *string `xml:"PartnerKey,omitempty" json:"PartnerKey,omitempty" yaml:"PartnerKey,omitempty"`
	Omgevingscode *string `xml:"Omgevingscode,omitempty" json:"Omgevingscode,omitempty" yaml:"Omgevingscode,omitempty"`
	SessionId     *string `xml:"SessionId,omitempty" json:"SessionId,omitempty" yaml:"SessionId,omitempty"`
	Mutatie       *string `xml:"Mutatie,omitempty" json:"Mutatie,omitempty" yaml:"Mutatie,omitempty"`
	Foutmelding   *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// DeleteVerkoopContractRegelResponse was auto-generated from WSDL.
type DeleteVerkoopContractRegelResponse struct {
	DeleteVerkoopContractRegelResult bool    `xml:"DeleteVerkoopContractRegelResult" json:"DeleteVerkoopContractRegelResult" yaml:"DeleteVerkoopContractRegelResult"`
	Foutmelding                      *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// DeleteVerkoopContractResponse was auto-generated from WSDL.
type DeleteVerkoopContractResponse struct {
	DeleteVerkoopContractResult bool    `xml:"DeleteVerkoopContractResult" json:"DeleteVerkoopContractResult" yaml:"DeleteVerkoopContractResult"`
	Foutmelding                 *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// DeleteVerkooporder was auto-generated from WSDL.
type DeleteVerkooporder struct {
	PartnerKey    *string `xml:"PartnerKey,omitempty" json:"PartnerKey,omitempty" yaml:"PartnerKey,omitempty"`
	Omgevingscode *string `xml:"Omgevingscode,omitempty" json:"Omgevingscode,omitempty" yaml:"Omgevingscode,omitempty"`
	SessionId     *string `xml:"SessionId,omitempty" json:"SessionId,omitempty" yaml:"SessionId,omitempty"`
	Mutatie       *string `xml:"Mutatie,omitempty" json:"Mutatie,omitempty" yaml:"Mutatie,omitempty"`
	Foutmelding   *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// DeleteVerkooporderRegel was auto-generated from WSDL.
type DeleteVerkooporderRegel struct {
	PartnerKey    *string `xml:"PartnerKey,omitempty" json:"PartnerKey,omitempty" yaml:"PartnerKey,omitempty"`
	Omgevingscode *string `xml:"Omgevingscode,omitempty" json:"Omgevingscode,omitempty" yaml:"Omgevingscode,omitempty"`
	SessionId     *string `xml:"SessionId,omitempty" json:"SessionId,omitempty" yaml:"SessionId,omitempty"`
	Mutatie       *string `xml:"Mutatie,omitempty" json:"Mutatie,omitempty" yaml:"Mutatie,omitempty"`
	Foutmelding   *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// DeleteVerkooporderRegelResponse was auto-generated from WSDL.
type DeleteVerkooporderRegelResponse struct {
	DeleteVerkooporderRegelResult bool    `xml:"DeleteVerkooporderRegelResult" json:"DeleteVerkooporderRegelResult" yaml:"DeleteVerkooporderRegelResult"`
	Foutmelding                   *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// DeleteVerkooporderResponse was auto-generated from WSDL.
type DeleteVerkooporderResponse struct {
	DeleteVerkooporderResult bool    `xml:"DeleteVerkooporderResult" json:"DeleteVerkooporderResult" yaml:"DeleteVerkooporderResult"`
	Foutmelding              *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// GetAdmInfo was auto-generated from WSDL.
type GetAdmInfo struct {
	PartnerKey    *string `xml:"PartnerKey,omitempty" json:"PartnerKey,omitempty" yaml:"PartnerKey,omitempty"`
	Omgevingscode *string `xml:"Omgevingscode,omitempty" json:"Omgevingscode,omitempty" yaml:"Omgevingscode,omitempty"`
	SessionId     *string `xml:"SessionId,omitempty" json:"SessionId,omitempty" yaml:"SessionId,omitempty"`
	Selectie      *string `xml:"Selectie,omitempty" json:"Selectie,omitempty" yaml:"Selectie,omitempty"`
	Records       *string `xml:"Records,omitempty" json:"Records,omitempty" yaml:"Records,omitempty"`
	Foutmelding   *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// GetAdmInfoResponse was auto-generated from WSDL.
type GetAdmInfoResponse struct {
	GetAdmInfoResult bool    `xml:"GetAdmInfoResult" json:"GetAdmInfoResult" yaml:"GetAdmInfoResult"`
	Records          *string `xml:"Records,omitempty" json:"Records,omitempty" yaml:"Records,omitempty"`
	Foutmelding      *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// GetLaatsteBoekingPeriode was auto-generated from WSDL.
type GetLaatsteBoekingPeriode struct {
	PartnerKey    *string `xml:"PartnerKey,omitempty" json:"PartnerKey,omitempty" yaml:"PartnerKey,omitempty"`
	Omgevingscode *string `xml:"Omgevingscode,omitempty" json:"Omgevingscode,omitempty" yaml:"Omgevingscode,omitempty"`
	SessionId     *string `xml:"SessionId,omitempty" json:"SessionId,omitempty" yaml:"SessionId,omitempty"`
	Selectie      *string `xml:"Selectie,omitempty" json:"Selectie,omitempty" yaml:"Selectie,omitempty"`
	Records       *string `xml:"Records,omitempty" json:"Records,omitempty" yaml:"Records,omitempty"`
	Foutmelding   *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// GetLaatsteBoekingPeriodeResponse was auto-generated from WSDL.
type GetLaatsteBoekingPeriodeResponse struct {
	GetLaatsteBoekingPeriodeResult bool    `xml:"GetLaatsteBoekingPeriodeResult" json:"GetLaatsteBoekingPeriodeResult" yaml:"GetLaatsteBoekingPeriodeResult"`
	Records                        *string `xml:"Records,omitempty" json:"Records,omitempty" yaml:"Records,omitempty"`
	Foutmelding                    *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// GetPredefindQuery was auto-generated from WSDL.
type GetPredefindQuery struct {
	PartnerKey    *string `xml:"PartnerKey,omitempty" json:"PartnerKey,omitempty" yaml:"PartnerKey,omitempty"`
	Omgevingscode *string `xml:"Omgevingscode,omitempty" json:"Omgevingscode,omitempty" yaml:"Omgevingscode,omitempty"`
	SessionId     *string `xml:"SessionId,omitempty" json:"SessionId,omitempty" yaml:"SessionId,omitempty"`
	Selectie      *string `xml:"Selectie,omitempty" json:"Selectie,omitempty" yaml:"Selectie,omitempty"`
	Records       *string `xml:"Records,omitempty" json:"Records,omitempty" yaml:"Records,omitempty"`
	Foutmelding   *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// GetPredefindQueryResponse was auto-generated from WSDL.
type GetPredefindQueryResponse struct {
	GetPredefindQueryResult bool    `xml:"GetPredefindQueryResult" json:"GetPredefindQueryResult" yaml:"GetPredefindQueryResult"`
	Records                 *string `xml:"Records,omitempty" json:"Records,omitempty" yaml:"Records,omitempty"`
	Foutmelding             *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// GetStamtabelRecords was auto-generated from WSDL.
type GetStamtabelRecords struct {
	PartnerKey    *string   `xml:"PartnerKey,omitempty" json:"PartnerKey,omitempty" yaml:"PartnerKey,omitempty"`
	Omgevingscode *string   `xml:"Omgevingscode,omitempty" json:"Omgevingscode,omitempty" yaml:"Omgevingscode,omitempty"`
	SessionId     *string   `xml:"SessionId,omitempty" json:"SessionId,omitempty" yaml:"SessionId,omitempty"`
	Selectie      *Selectie `xml:"Selectie,omitempty" json:"Selectie,omitempty" yaml:"Selectie,omitempty"`
	Records       *string   `xml:"Records,omitempty" json:"Records,omitempty" yaml:"Records,omitempty"`
	Foutmelding   *string   `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// GetStamtabelRecordsResponse was auto-generated from WSDL.
type GetStamtabelRecordsResponse struct {
	GetStamtabelRecordsResult bool                               `xml:"GetStamtabelRecordsResult" json:"GetStamtabelRecordsResult" yaml:"GetStamtabelRecordsResult"`
	Records                   GetStamtabelRecordsResponseRecords `xml:"Records,omitempty" json:"Records,omitempty" yaml:"Records,omitempty"`
	Foutmelding               *string                            `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// GetTimeStamp was auto-generated from WSDL.
type GetTimeStamp struct {
	PartnerKey    *string `xml:"PartnerKey,omitempty" json:"PartnerKey,omitempty" yaml:"PartnerKey,omitempty"`
	Omgevingscode *string `xml:"Omgevingscode,omitempty" json:"Omgevingscode,omitempty" yaml:"Omgevingscode,omitempty"`
	SessionId     *string `xml:"SessionId,omitempty" json:"SessionId,omitempty" yaml:"SessionId,omitempty"`
	TimeStamp     *string `xml:"TimeStamp,omitempty" json:"TimeStamp,omitempty" yaml:"TimeStamp,omitempty"`
	Foutmelding   *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// GetTimeStampResponse was auto-generated from WSDL.
type GetTimeStampResponse struct {
	GetTimeStampResult bool    `xml:"GetTimeStampResult" json:"GetTimeStampResult" yaml:"GetTimeStampResult"`
	TimeStamp          *string `xml:"TimeStamp,omitempty" json:"TimeStamp,omitempty" yaml:"TimeStamp,omitempty"`
	Foutmelding        *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// GetiMUISVersion was auto-generated from WSDL.
type GetiMUISVersion struct {
	PartnerKey    *string `xml:"PartnerKey,omitempty" json:"PartnerKey,omitempty" yaml:"PartnerKey,omitempty"`
	Omgevingscode *string `xml:"Omgevingscode,omitempty" json:"Omgevingscode,omitempty" yaml:"Omgevingscode,omitempty"`
	IMUISVersion  *string `xml:"iMUISVersion,omitempty" json:"iMUISVersion,omitempty" yaml:"iMUISVersion,omitempty"`
	Foutmelding   *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// GetiMUISVersionResponse was auto-generated from WSDL.
type GetiMUISVersionResponse struct {
	GetiMUISVersionResult bool    `xml:"GetiMUISVersionResult" json:"GetiMUISVersionResult" yaml:"GetiMUISVersionResult"`
	IMUISVersion          *string `xml:"iMUISVersion,omitempty" json:"iMUISVersion,omitempty" yaml:"iMUISVersion,omitempty"`
	Foutmelding           *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// KeepSession was auto-generated from WSDL.
type KeepSession struct {
	PartnerKey    *string `xml:"PartnerKey,omitempty" json:"PartnerKey,omitempty" yaml:"PartnerKey,omitempty"`
	Omgevingscode *string `xml:"Omgevingscode,omitempty" json:"Omgevingscode,omitempty" yaml:"Omgevingscode,omitempty"`
	SessionId     *string `xml:"SessionId,omitempty" json:"SessionId,omitempty" yaml:"SessionId,omitempty"`
	Foutmelding   *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// KeepSessionResponse was auto-generated from WSDL.
type KeepSessionResponse struct {
	KeepSessionResult bool    `xml:"KeepSessionResult" json:"KeepSessionResult" yaml:"KeepSessionResult"`
	Foutmelding       *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// Login was auto-generated from WSDL.
type Login struct {
	PartnerKey    *string `xml:"PartnerKey,omitempty" json:"PartnerKey,omitempty" yaml:"PartnerKey,omitempty"`
	Omgevingscode *string `xml:"Omgevingscode,omitempty" json:"Omgevingscode,omitempty" yaml:"Omgevingscode,omitempty"`
	SessionId     *string `xml:"SessionId,omitempty" json:"SessionId,omitempty" yaml:"SessionId,omitempty"`
	Foutmelding   *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// LoginResponse was auto-generated from WSDL.
type LoginResponse struct {
	LoginResult bool    `xml:"LoginResult" json:"LoginResult" yaml:"LoginResult"`
	SessionId   *string `xml:"SessionId,omitempty" json:"SessionId,omitempty" yaml:"SessionId,omitempty"`
	Foutmelding *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// Logout was auto-generated from WSDL.
type Logout struct {
	PartnerKey    *string `xml:"PartnerKey,omitempty" json:"PartnerKey,omitempty" yaml:"PartnerKey,omitempty"`
	Omgevingscode *string `xml:"Omgevingscode,omitempty" json:"Omgevingscode,omitempty" yaml:"Omgevingscode,omitempty"`
	SessionId     *string `xml:"SessionId,omitempty" json:"SessionId,omitempty" yaml:"SessionId,omitempty"`
	Foutmelding   *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// LogoutResponse was auto-generated from WSDL.
type LogoutResponse struct {
	LogoutResult bool    `xml:"LogoutResult" json:"LogoutResult" yaml:"LogoutResult"`
	Foutmelding  *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// UpdateInkooporderRegel was auto-generated from WSDL.
type UpdateInkooporderRegel struct {
	PartnerKey    *string `xml:"PartnerKey,omitempty" json:"PartnerKey,omitempty" yaml:"PartnerKey,omitempty"`
	Omgevingscode *string `xml:"Omgevingscode,omitempty" json:"Omgevingscode,omitempty" yaml:"Omgevingscode,omitempty"`
	SessionId     *string `xml:"SessionId,omitempty" json:"SessionId,omitempty" yaml:"SessionId,omitempty"`
	Mutatie       *string `xml:"Mutatie,omitempty" json:"Mutatie,omitempty" yaml:"Mutatie,omitempty"`
	Foutmelding   *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// UpdateInkooporderRegelResponse was auto-generated from WSDL.
type UpdateInkooporderRegelResponse struct {
	UpdateInkooporderRegelResult bool    `xml:"UpdateInkooporderRegelResult" json:"UpdateInkooporderRegelResult" yaml:"UpdateInkooporderRegelResult"`
	Foutmelding                  *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// UpdateJournaalpost was auto-generated from WSDL.
type UpdateJournaalpost struct {
	PartnerKey    *string `xml:"PartnerKey,omitempty" json:"PartnerKey,omitempty" yaml:"PartnerKey,omitempty"`
	Omgevingscode *string `xml:"Omgevingscode,omitempty" json:"Omgevingscode,omitempty" yaml:"Omgevingscode,omitempty"`
	SessionId     *string `xml:"SessionId,omitempty" json:"SessionId,omitempty" yaml:"SessionId,omitempty"`
	Primarykey    *string `xml:"Primarykey,omitempty" json:"Primarykey,omitempty" yaml:"Primarykey,omitempty"`
	Journaalpost  *string `xml:"Journaalpost,omitempty" json:"Journaalpost,omitempty" yaml:"Journaalpost,omitempty"`
	Foutmelding   *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// UpdateJournaalpostResponse was auto-generated from WSDL.
type UpdateJournaalpostResponse struct {
	UpdateJournaalpostResult bool    `xml:"UpdateJournaalpostResult" json:"UpdateJournaalpostResult" yaml:"UpdateJournaalpostResult"`
	Foutmelding              *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// UpdateStamtabelRecord was auto-generated from WSDL.
type UpdateStamtabelRecord struct {
	PartnerKey    *string                       `xml:"PartnerKey,omitempty" json:"PartnerKey,omitempty" yaml:"PartnerKey,omitempty"`
	Omgevingscode *string                       `xml:"Omgevingscode,omitempty" json:"Omgevingscode,omitempty" yaml:"Omgevingscode,omitempty"`
	SessionId     *string                       `xml:"SessionId,omitempty" json:"SessionId,omitempty" yaml:"SessionId,omitempty"`
	Mutatie       *UpdateStamTabelRecordMutatie `xml:"Mutatie,omitempty" json:"Mutatie,omitempty" yaml:"Mutatie,omitempty"`
	Foutmelding   *string                       `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// UpdateStamtabelRecordResponse was auto-generated from WSDL.
type UpdateStamtabelRecordResponse struct {
	UpdateStamtabelRecordResult bool    `xml:"UpdateStamtabelRecordResult" json:"UpdateStamtabelRecordResult" yaml:"UpdateStamtabelRecordResult"`
	Foutmelding                 *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// UpdateVerkoopContractRegel was auto-generated from WSDL.
type UpdateVerkoopContractRegel struct {
	PartnerKey    *string `xml:"PartnerKey,omitempty" json:"PartnerKey,omitempty" yaml:"PartnerKey,omitempty"`
	Omgevingscode *string `xml:"Omgevingscode,omitempty" json:"Omgevingscode,omitempty" yaml:"Omgevingscode,omitempty"`
	SessionId     *string `xml:"SessionId,omitempty" json:"SessionId,omitempty" yaml:"SessionId,omitempty"`
	Mutatie       *string `xml:"Mutatie,omitempty" json:"Mutatie,omitempty" yaml:"Mutatie,omitempty"`
	Foutmelding   *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// UpdateVerkoopContractRegelResponse was auto-generated from WSDL.
type UpdateVerkoopContractRegelResponse struct {
	UpdateVerkoopContractRegelResult bool    `xml:"UpdateVerkoopContractRegelResult" json:"UpdateVerkoopContractRegelResult" yaml:"UpdateVerkoopContractRegelResult"`
	Foutmelding                      *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// UpdateVerkooporderPickBonGepakt was auto-generated from WSDL.
type UpdateVerkooporderPickBonGepakt struct {
	PartnerKey    *string `xml:"PartnerKey,omitempty" json:"PartnerKey,omitempty" yaml:"PartnerKey,omitempty"`
	Omgevingscode *string `xml:"Omgevingscode,omitempty" json:"Omgevingscode,omitempty" yaml:"Omgevingscode,omitempty"`
	SessionId     *string `xml:"SessionId,omitempty" json:"SessionId,omitempty" yaml:"SessionId,omitempty"`
	Selectie      *string `xml:"Selectie,omitempty" json:"Selectie,omitempty" yaml:"Selectie,omitempty"`
	Foutmelding   *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// UpdateVerkooporderPickBonGepaktResponse was auto-generated from
// WSDL.
type UpdateVerkooporderPickBonGepaktResponse struct {
	UpdateVerkooporderPickBonGepaktResult bool    `xml:"UpdateVerkooporderPickBonGepaktResult" json:"UpdateVerkooporderPickBonGepaktResult" yaml:"UpdateVerkooporderPickBonGepaktResult"`
	Foutmelding                           *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// UpdateVerkooporderPickbonGereed was auto-generated from WSDL.
type UpdateVerkooporderPickbonGereed struct {
	PartnerKey    *string `xml:"PartnerKey,omitempty" json:"PartnerKey,omitempty" yaml:"PartnerKey,omitempty"`
	Omgevingscode *string `xml:"Omgevingscode,omitempty" json:"Omgevingscode,omitempty" yaml:"Omgevingscode,omitempty"`
	SessionId     *string `xml:"SessionId,omitempty" json:"SessionId,omitempty" yaml:"SessionId,omitempty"`
	Selectie      *string `xml:"Selectie,omitempty" json:"Selectie,omitempty" yaml:"Selectie,omitempty"`
	Foutmelding   *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// UpdateVerkooporderPickbonGereedResponse was auto-generated from
// WSDL.
type UpdateVerkooporderPickbonGereedResponse struct {
	UpdateVerkooporderPickbonGereedResult bool    `xml:"UpdateVerkooporderPickbonGereedResult" json:"UpdateVerkooporderPickbonGereedResult" yaml:"UpdateVerkooporderPickbonGereedResult"`
	Foutmelding                           *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// UpdateVerkooporderRegel was auto-generated from WSDL.
type UpdateVerkooporderRegel struct {
	PartnerKey    *string `xml:"PartnerKey,omitempty" json:"PartnerKey,omitempty" yaml:"PartnerKey,omitempty"`
	Omgevingscode *string `xml:"Omgevingscode,omitempty" json:"Omgevingscode,omitempty" yaml:"Omgevingscode,omitempty"`
	SessionId     *string `xml:"SessionId,omitempty" json:"SessionId,omitempty" yaml:"SessionId,omitempty"`
	Mutatie       *string `xml:"Mutatie,omitempty" json:"Mutatie,omitempty" yaml:"Mutatie,omitempty"`
	Foutmelding   *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// UpdateVerkooporderRegelResponse was auto-generated from WSDL.
type UpdateVerkooporderRegelResponse struct {
	UpdateVerkooporderRegelResult bool    `xml:"UpdateVerkooporderRegelResult" json:"UpdateVerkooporderRegelResult" yaml:"UpdateVerkooporderRegelResult"`
	Foutmelding                   *string `xml:"Foutmelding,omitempty" json:"Foutmelding,omitempty" yaml:"Foutmelding,omitempty"`
}

// Operation wrapper for CheckConnection.
// OperationCheckConnectionSoapIn was auto-generated from WSDL.
type OperationCheckConnectionSoapIn struct {
	CheckConnection *CheckConnection `xml:"CheckConnection,omitempty" json:"CheckConnection,omitempty" yaml:"CheckConnection,omitempty"`
}

// Operation wrapper for CheckConnection.
// OperationCheckConnectionSoapOut was auto-generated from WSDL.
type OperationCheckConnectionSoapOut struct {
	CheckConnectionResponse *CheckConnectionResponse `xml:"CheckConnectionResponse,omitempty" json:"CheckConnectionResponse,omitempty" yaml:"CheckConnectionResponse,omitempty"`
}

// Operation wrapper for CreateGoederenontvangst.
// OperationCreateGoederenontvangstSoapIn was auto-generated from
// WSDL.
type OperationCreateGoederenontvangstSoapIn struct {
	CreateGoederenontvangst *CreateGoederenontvangst `xml:"CreateGoederenontvangst,omitempty" json:"CreateGoederenontvangst,omitempty" yaml:"CreateGoederenontvangst,omitempty"`
}

// Operation wrapper for CreateGoederenontvangst.
// OperationCreateGoederenontvangstSoapOut was auto-generated from
// WSDL.
type OperationCreateGoederenontvangstSoapOut struct {
	CreateGoederenontvangstResponse *CreateGoederenontvangstResponse `xml:"CreateGoederenontvangstResponse,omitempty" json:"CreateGoederenontvangstResponse,omitempty" yaml:"CreateGoederenontvangstResponse,omitempty"`
}

// Operation wrapper for CreateInkoopOrder.
// OperationCreateInkoopOrderSoapIn was auto-generated from WSDL.
type OperationCreateInkoopOrderSoapIn struct {
	CreateInkoopOrder *CreateInkoopOrder `xml:"CreateInkoopOrder,omitempty" json:"CreateInkoopOrder,omitempty" yaml:"CreateInkoopOrder,omitempty"`
}

// Operation wrapper for CreateInkoopOrder.
// OperationCreateInkoopOrderSoapOut was auto-generated from WSDL.
type OperationCreateInkoopOrderSoapOut struct {
	CreateInkoopOrderResponse *CreateInkoopOrderResponse `xml:"CreateInkoopOrderResponse,omitempty" json:"CreateInkoopOrderResponse,omitempty" yaml:"CreateInkoopOrderResponse,omitempty"`
}

// Operation wrapper for CreateInkoopfactuur.
// OperationCreateInkoopfactuurSoapIn was auto-generated from WSDL.
type OperationCreateInkoopfactuurSoapIn struct {
	CreateInkoopfactuur *CreateInkoopfactuur `xml:"CreateInkoopfactuur,omitempty" json:"CreateInkoopfactuur,omitempty" yaml:"CreateInkoopfactuur,omitempty"`
}

// Operation wrapper for CreateInkoopfactuur.
// OperationCreateInkoopfactuurSoapOut was auto-generated from
// WSDL.
type OperationCreateInkoopfactuurSoapOut struct {
	CreateInkoopfactuurResponse *CreateInkoopfactuurResponse `xml:"CreateInkoopfactuurResponse,omitempty" json:"CreateInkoopfactuurResponse,omitempty" yaml:"CreateInkoopfactuurResponse,omitempty"`
}

// Operation wrapper for CreateInkooporderRegel.
// OperationCreateInkooporderRegelSoapIn was auto-generated from
// WSDL.
type OperationCreateInkooporderRegelSoapIn struct {
	CreateInkooporderRegel *CreateInkooporderRegel `xml:"CreateInkooporderRegel,omitempty" json:"CreateInkooporderRegel,omitempty" yaml:"CreateInkooporderRegel,omitempty"`
}

// Operation wrapper for CreateInkooporderRegel.
// OperationCreateInkooporderRegelSoapOut was auto-generated from
// WSDL.
type OperationCreateInkooporderRegelSoapOut struct {
	CreateInkooporderRegelResponse *CreateInkooporderRegelResponse `xml:"CreateInkooporderRegelResponse,omitempty" json:"CreateInkooporderRegelResponse,omitempty" yaml:"CreateInkooporderRegelResponse,omitempty"`
}

// Operation wrapper for CreateJournaalpost.
// OperationCreateJournaalpostSoapIn was auto-generated from WSDL.
type OperationCreateJournaalpostSoapIn struct {
	CreateJournaalpost *CreateJournaalpost `xml:"CreateJournaalpost,omitempty" json:"CreateJournaalpost,omitempty" yaml:"CreateJournaalpost,omitempty"`
}

// Operation wrapper for CreateJournaalpost.
// OperationCreateJournaalpostSoapOut was auto-generated from WSDL.
type OperationCreateJournaalpostSoapOut struct {
	CreateJournaalpostResponse *CreateJournaalpostResponse `xml:"CreateJournaalpostResponse,omitempty" json:"CreateJournaalpostResponse,omitempty" yaml:"CreateJournaalpostResponse,omitempty"`
}

// Operation wrapper for CreateSpitsfactuur.
// OperationCreateSpitsfactuurSoapIn was auto-generated from WSDL.
type OperationCreateSpitsfactuurSoapIn struct {
	CreateSpitsfactuur *CreateSpitsfactuur `xml:"CreateSpitsfactuur,omitempty" json:"CreateSpitsfactuur,omitempty" yaml:"CreateSpitsfactuur,omitempty"`
}

// Operation wrapper for CreateSpitsfactuur.
// OperationCreateSpitsfactuurSoapOut was auto-generated from WSDL.
type OperationCreateSpitsfactuurSoapOut struct {
	CreateSpitsfactuurResponse *CreateSpitsfactuurResponse `xml:"CreateSpitsfactuurResponse,omitempty" json:"CreateSpitsfactuurResponse,omitempty" yaml:"CreateSpitsfactuurResponse,omitempty"`
}

// Operation wrapper for CreateStamTabelRecord.
// OperationCreateStamTabelRecordSoapIn was auto-generated from
// WSDL.
type OperationCreateStamTabelRecordSoapIn struct {
	CreateStamTabelRecord *CreateStamTabelRecord `xml:"CreateStamTabelRecord,omitempty" json:"CreateStamTabelRecord,omitempty" yaml:"CreateStamTabelRecord,omitempty"`
}

// Operation wrapper for CreateStamTabelRecord.
// OperationCreateStamTabelRecordSoapOut was auto-generated from
// WSDL.
type OperationCreateStamTabelRecordSoapOut struct {
	CreateStamTabelRecordResponse *CreateStamTabelRecordResponse `xml:"CreateStamTabelRecordResponse,omitempty" json:"CreateStamTabelRecordResponse,omitempty" yaml:"CreateStamTabelRecordResponse,omitempty"`
}

// Operation wrapper for CreateVerkoopContract.
// OperationCreateVerkoopContractSoapIn was auto-generated from
// WSDL.
type OperationCreateVerkoopContractSoapIn struct {
	CreateVerkoopContract *CreateVerkoopContract `xml:"CreateVerkoopContract,omitempty" json:"CreateVerkoopContract,omitempty" yaml:"CreateVerkoopContract,omitempty"`
}

// Operation wrapper for CreateVerkoopContract.
// OperationCreateVerkoopContractSoapOut was auto-generated from
// WSDL.
type OperationCreateVerkoopContractSoapOut struct {
	CreateVerkoopContractResponse *CreateVerkoopContractResponse `xml:"CreateVerkoopContractResponse,omitempty" json:"CreateVerkoopContractResponse,omitempty" yaml:"CreateVerkoopContractResponse,omitempty"`
}

// Operation wrapper for CreateVerkoopContractRegel.
// OperationCreateVerkoopContractRegelSoapIn was auto-generated
// from WSDL.
type OperationCreateVerkoopContractRegelSoapIn struct {
	CreateVerkoopContractRegel *CreateVerkoopContractRegel `xml:"CreateVerkoopContractRegel,omitempty" json:"CreateVerkoopContractRegel,omitempty" yaml:"CreateVerkoopContractRegel,omitempty"`
}

// Operation wrapper for CreateVerkoopContractRegel.
// OperationCreateVerkoopContractRegelSoapOut was auto-generated
// from WSDL.
type OperationCreateVerkoopContractRegelSoapOut struct {
	CreateVerkoopContractRegelResponse *CreateVerkoopContractRegelResponse `xml:"CreateVerkoopContractRegelResponse,omitempty" json:"CreateVerkoopContractRegelResponse,omitempty" yaml:"CreateVerkoopContractRegelResponse,omitempty"`
}

// Operation wrapper for CreateVerkoopOrder.
// OperationCreateVerkoopOrderSoapIn was auto-generated from WSDL.
type OperationCreateVerkoopOrderSoapIn struct {
	CreateVerkoopOrder *CreateVerkoopOrder `xml:"CreateVerkoopOrder,omitempty" json:"CreateVerkoopOrder,omitempty" yaml:"CreateVerkoopOrder,omitempty"`
}

// Operation wrapper for CreateVerkoopOrder.
// OperationCreateVerkoopOrderSoapOut was auto-generated from WSDL.
type OperationCreateVerkoopOrderSoapOut struct {
	CreateVerkoopOrderResponse *CreateVerkoopOrderResponse `xml:"CreateVerkoopOrderResponse,omitempty" json:"CreateVerkoopOrderResponse,omitempty" yaml:"CreateVerkoopOrderResponse,omitempty"`
}

// Operation wrapper for CreateVerkooporderPickbon.
// OperationCreateVerkooporderPickbonSoapIn was auto-generated
// from WSDL.
type OperationCreateVerkooporderPickbonSoapIn struct {
	CreateVerkooporderPickbon *CreateVerkooporderPickbon `xml:"CreateVerkooporderPickbon,omitempty" json:"CreateVerkooporderPickbon,omitempty" yaml:"CreateVerkooporderPickbon,omitempty"`
}

// Operation wrapper for CreateVerkooporderPickbon.
// OperationCreateVerkooporderPickbonSoapOut was auto-generated
// from WSDL.
type OperationCreateVerkooporderPickbonSoapOut struct {
	CreateVerkooporderPickbonResponse *CreateVerkooporderPickbonResponse `xml:"CreateVerkooporderPickbonResponse,omitempty" json:"CreateVerkooporderPickbonResponse,omitempty" yaml:"CreateVerkooporderPickbonResponse,omitempty"`
}

// Operation wrapper for CreateVerkooporderRegel.
// OperationCreateVerkooporderRegelSoapIn was auto-generated from
// WSDL.
type OperationCreateVerkooporderRegelSoapIn struct {
	CreateVerkooporderRegel *CreateVerkooporderRegel `xml:"CreateVerkooporderRegel,omitempty" json:"CreateVerkooporderRegel,omitempty" yaml:"CreateVerkooporderRegel,omitempty"`
}

// Operation wrapper for CreateVerkooporderRegel.
// OperationCreateVerkooporderRegelSoapOut was auto-generated from
// WSDL.
type OperationCreateVerkooporderRegelSoapOut struct {
	CreateVerkooporderRegelResponse *CreateVerkooporderRegelResponse `xml:"CreateVerkooporderRegelResponse,omitempty" json:"CreateVerkooporderRegelResponse,omitempty" yaml:"CreateVerkooporderRegelResponse,omitempty"`
}

// Operation wrapper for DeleteInkooporder.
// OperationDeleteInkooporderSoapIn was auto-generated from WSDL.
type OperationDeleteInkooporderSoapIn struct {
	DeleteInkooporder *DeleteInkooporder `xml:"DeleteInkooporder,omitempty" json:"DeleteInkooporder,omitempty" yaml:"DeleteInkooporder,omitempty"`
}

// Operation wrapper for DeleteInkooporder.
// OperationDeleteInkooporderSoapOut was auto-generated from WSDL.
type OperationDeleteInkooporderSoapOut struct {
	DeleteInkooporderResponse *DeleteInkooporderResponse `xml:"DeleteInkooporderResponse,omitempty" json:"DeleteInkooporderResponse,omitempty" yaml:"DeleteInkooporderResponse,omitempty"`
}

// Operation wrapper for DeleteInkooporderRegel.
// OperationDeleteInkooporderRegelSoapIn was auto-generated from
// WSDL.
type OperationDeleteInkooporderRegelSoapIn struct {
	DeleteInkooporderRegel *DeleteInkooporderRegel `xml:"DeleteInkooporderRegel,omitempty" json:"DeleteInkooporderRegel,omitempty" yaml:"DeleteInkooporderRegel,omitempty"`
}

// Operation wrapper for DeleteInkooporderRegel.
// OperationDeleteInkooporderRegelSoapOut was auto-generated from
// WSDL.
type OperationDeleteInkooporderRegelSoapOut struct {
	DeleteInkooporderRegelResponse *DeleteInkooporderRegelResponse `xml:"DeleteInkooporderRegelResponse,omitempty" json:"DeleteInkooporderRegelResponse,omitempty" yaml:"DeleteInkooporderRegelResponse,omitempty"`
}

// Operation wrapper for DeleteJournaalpost.
// OperationDeleteJournaalpostSoapIn was auto-generated from WSDL.
type OperationDeleteJournaalpostSoapIn struct {
	DeleteJournaalpost *DeleteJournaalpost `xml:"DeleteJournaalpost,omitempty" json:"DeleteJournaalpost,omitempty" yaml:"DeleteJournaalpost,omitempty"`
}

// Operation wrapper for DeleteJournaalpost.
// OperationDeleteJournaalpostSoapOut was auto-generated from WSDL.
type OperationDeleteJournaalpostSoapOut struct {
	DeleteJournaalpostResponse *DeleteJournaalpostResponse `xml:"DeleteJournaalpostResponse,omitempty" json:"DeleteJournaalpostResponse,omitempty" yaml:"DeleteJournaalpostResponse,omitempty"`
}

// Operation wrapper for DeleteStamtabelRecord.
// OperationDeleteStamtabelRecordSoapIn was auto-generated from
// WSDL.
type OperationDeleteStamtabelRecordSoapIn struct {
	DeleteStamtabelRecord *DeleteStamtabelRecord `xml:"DeleteStamtabelRecord,omitempty" json:"DeleteStamtabelRecord,omitempty" yaml:"DeleteStamtabelRecord,omitempty"`
}

// Operation wrapper for DeleteStamtabelRecord.
// OperationDeleteStamtabelRecordSoapOut was auto-generated from
// WSDL.
type OperationDeleteStamtabelRecordSoapOut struct {
	DeleteStamtabelRecordResponse *DeleteStamtabelRecordResponse `xml:"DeleteStamtabelRecordResponse,omitempty" json:"DeleteStamtabelRecordResponse,omitempty" yaml:"DeleteStamtabelRecordResponse,omitempty"`
}

// Operation wrapper for DeleteVerkoopContract.
// OperationDeleteVerkoopContractSoapIn was auto-generated from
// WSDL.
type OperationDeleteVerkoopContractSoapIn struct {
	DeleteVerkoopContract *DeleteVerkoopContract `xml:"DeleteVerkoopContract,omitempty" json:"DeleteVerkoopContract,omitempty" yaml:"DeleteVerkoopContract,omitempty"`
}

// Operation wrapper for DeleteVerkoopContract.
// OperationDeleteVerkoopContractSoapOut was auto-generated from
// WSDL.
type OperationDeleteVerkoopContractSoapOut struct {
	DeleteVerkoopContractResponse *DeleteVerkoopContractResponse `xml:"DeleteVerkoopContractResponse,omitempty" json:"DeleteVerkoopContractResponse,omitempty" yaml:"DeleteVerkoopContractResponse,omitempty"`
}

// Operation wrapper for DeleteVerkoopContractRegel.
// OperationDeleteVerkoopContractRegelSoapIn was auto-generated
// from WSDL.
type OperationDeleteVerkoopContractRegelSoapIn struct {
	DeleteVerkoopContractRegel *DeleteVerkoopContractRegel `xml:"DeleteVerkoopContractRegel,omitempty" json:"DeleteVerkoopContractRegel,omitempty" yaml:"DeleteVerkoopContractRegel,omitempty"`
}

// Operation wrapper for DeleteVerkoopContractRegel.
// OperationDeleteVerkoopContractRegelSoapOut was auto-generated
// from WSDL.
type OperationDeleteVerkoopContractRegelSoapOut struct {
	DeleteVerkoopContractRegelResponse *DeleteVerkoopContractRegelResponse `xml:"DeleteVerkoopContractRegelResponse,omitempty" json:"DeleteVerkoopContractRegelResponse,omitempty" yaml:"DeleteVerkoopContractRegelResponse,omitempty"`
}

// Operation wrapper for DeleteVerkooporder.
// OperationDeleteVerkooporderSoapIn was auto-generated from WSDL.
type OperationDeleteVerkooporderSoapIn struct {
	DeleteVerkooporder *DeleteVerkooporder `xml:"DeleteVerkooporder,omitempty" json:"DeleteVerkooporder,omitempty" yaml:"DeleteVerkooporder,omitempty"`
}

// Operation wrapper for DeleteVerkooporder.
// OperationDeleteVerkooporderSoapOut was auto-generated from WSDL.
type OperationDeleteVerkooporderSoapOut struct {
	DeleteVerkooporderResponse *DeleteVerkooporderResponse `xml:"DeleteVerkooporderResponse,omitempty" json:"DeleteVerkooporderResponse,omitempty" yaml:"DeleteVerkooporderResponse,omitempty"`
}

// Operation wrapper for DeleteVerkooporderRegel.
// OperationDeleteVerkooporderRegelSoapIn was auto-generated from
// WSDL.
type OperationDeleteVerkooporderRegelSoapIn struct {
	DeleteVerkooporderRegel *DeleteVerkooporderRegel `xml:"DeleteVerkooporderRegel,omitempty" json:"DeleteVerkooporderRegel,omitempty" yaml:"DeleteVerkooporderRegel,omitempty"`
}

// Operation wrapper for DeleteVerkooporderRegel.
// OperationDeleteVerkooporderRegelSoapOut was auto-generated from
// WSDL.
type OperationDeleteVerkooporderRegelSoapOut struct {
	DeleteVerkooporderRegelResponse *DeleteVerkooporderRegelResponse `xml:"DeleteVerkooporderRegelResponse,omitempty" json:"DeleteVerkooporderRegelResponse,omitempty" yaml:"DeleteVerkooporderRegelResponse,omitempty"`
}

// Operation wrapper for GetAdmInfo.
// OperationGetAdmInfoSoapIn was auto-generated from WSDL.
type OperationGetAdmInfoSoapIn struct {
	GetAdmInfo *GetAdmInfo `xml:"GetAdmInfo,omitempty" json:"GetAdmInfo,omitempty" yaml:"GetAdmInfo,omitempty"`
}

// Operation wrapper for GetAdmInfo.
// OperationGetAdmInfoSoapOut was auto-generated from WSDL.
type OperationGetAdmInfoSoapOut struct {
	GetAdmInfoResponse *GetAdmInfoResponse `xml:"GetAdmInfoResponse,omitempty" json:"GetAdmInfoResponse,omitempty" yaml:"GetAdmInfoResponse,omitempty"`
}

// Operation wrapper for GetLaatsteBoekingPeriode.
// OperationGetLaatsteBoekingPeriodeSoapIn was auto-generated from
// WSDL.
type OperationGetLaatsteBoekingPeriodeSoapIn struct {
	GetLaatsteBoekingPeriode *GetLaatsteBoekingPeriode `xml:"GetLaatsteBoekingPeriode,omitempty" json:"GetLaatsteBoekingPeriode,omitempty" yaml:"GetLaatsteBoekingPeriode,omitempty"`
}

// Operation wrapper for GetLaatsteBoekingPeriode.
// OperationGetLaatsteBoekingPeriodeSoapOut was auto-generated
// from WSDL.
type OperationGetLaatsteBoekingPeriodeSoapOut struct {
	GetLaatsteBoekingPeriodeResponse *GetLaatsteBoekingPeriodeResponse `xml:"GetLaatsteBoekingPeriodeResponse,omitempty" json:"GetLaatsteBoekingPeriodeResponse,omitempty" yaml:"GetLaatsteBoekingPeriodeResponse,omitempty"`
}

// Operation wrapper for GetPredefindQuery.
// OperationGetPredefindQuerySoapIn was auto-generated from WSDL.
type OperationGetPredefindQuerySoapIn struct {
	GetPredefindQuery *GetPredefindQuery `xml:"GetPredefindQuery,omitempty" json:"GetPredefindQuery,omitempty" yaml:"GetPredefindQuery,omitempty"`
}

// Operation wrapper for GetPredefindQuery.
// OperationGetPredefindQuerySoapOut was auto-generated from WSDL.
type OperationGetPredefindQuerySoapOut struct {
	GetPredefindQueryResponse *GetPredefindQueryResponse `xml:"GetPredefindQueryResponse,omitempty" json:"GetPredefindQueryResponse,omitempty" yaml:"GetPredefindQueryResponse,omitempty"`
}

// Operation wrapper for GetStamtabelRecords.
// OperationGetStamtabelRecordsSoapIn was auto-generated from WSDL.
type OperationGetStamtabelRecordsSoapIn struct {
	GetStamtabelRecords *GetStamtabelRecords `xml:"GetStamtabelRecords,omitempty" json:"GetStamtabelRecords,omitempty" yaml:"GetStamtabelRecords,omitempty"`
}

// Operation wrapper for GetStamtabelRecords.
// OperationGetStamtabelRecordsSoapOut was auto-generated from
// WSDL.
type OperationGetStamtabelRecordsSoapOut struct {
	GetStamtabelRecordsResponse *GetStamtabelRecordsResponse `xml:"GetStamtabelRecordsResponse,omitempty" json:"GetStamtabelRecordsResponse,omitempty" yaml:"GetStamtabelRecordsResponse,omitempty"`
}

// Operation wrapper for GetTimeStamp.
// OperationGetTimeStampSoapIn was auto-generated from WSDL.
type OperationGetTimeStampSoapIn struct {
	GetTimeStamp *GetTimeStamp `xml:"GetTimeStamp,omitempty" json:"GetTimeStamp,omitempty" yaml:"GetTimeStamp,omitempty"`
}

// Operation wrapper for GetTimeStamp.
// OperationGetTimeStampSoapOut was auto-generated from WSDL.
type OperationGetTimeStampSoapOut struct {
	GetTimeStampResponse *GetTimeStampResponse `xml:"GetTimeStampResponse,omitempty" json:"GetTimeStampResponse,omitempty" yaml:"GetTimeStampResponse,omitempty"`
}

// Operation wrapper for GetiMUISVersion.
// OperationGetiMUISVersionSoapIn was auto-generated from WSDL.
type OperationGetiMUISVersionSoapIn struct {
	GetiMUISVersion *GetiMUISVersion `xml:"GetiMUISVersion,omitempty" json:"GetiMUISVersion,omitempty" yaml:"GetiMUISVersion,omitempty"`
}

// Operation wrapper for GetiMUISVersion.
// OperationGetiMUISVersionSoapOut was auto-generated from WSDL.
type OperationGetiMUISVersionSoapOut struct {
	GetiMUISVersionResponse *GetiMUISVersionResponse `xml:"GetiMUISVersionResponse,omitempty" json:"GetiMUISVersionResponse,omitempty" yaml:"GetiMUISVersionResponse,omitempty"`
}

// Operation wrapper for KeepSession.
// OperationKeepSessionSoapIn was auto-generated from WSDL.
type OperationKeepSessionSoapIn struct {
	KeepSession *KeepSession `xml:"KeepSession,omitempty" json:"KeepSession,omitempty" yaml:"KeepSession,omitempty"`
}

// Operation wrapper for KeepSession.
// OperationKeepSessionSoapOut was auto-generated from WSDL.
type OperationKeepSessionSoapOut struct {
	KeepSessionResponse *KeepSessionResponse `xml:"KeepSessionResponse,omitempty" json:"KeepSessionResponse,omitempty" yaml:"KeepSessionResponse,omitempty"`
}

// Operation wrapper for Login.
// OperationLoginSoapIn was auto-generated from WSDL.
type OperationLoginSoapIn struct {
	Login *Login `xml:"Login,omitempty" json:"Login,omitempty" yaml:"Login,omitempty"`
}

// Operation wrapper for Login.
// OperationLoginSoapOut was auto-generated from WSDL.
type OperationLoginSoapOut struct {
	LoginResponse *LoginResponse `xml:"LoginResponse,omitempty" json:"LoginResponse,omitempty" yaml:"LoginResponse,omitempty"`
}

// Operation wrapper for Logout.
// OperationLogoutSoapIn was auto-generated from WSDL.
type OperationLogoutSoapIn struct {
	Logout *Logout `xml:"Logout,omitempty" json:"Logout,omitempty" yaml:"Logout,omitempty"`
}

// Operation wrapper for Logout.
// OperationLogoutSoapOut was auto-generated from WSDL.
type OperationLogoutSoapOut struct {
	LogoutResponse *LogoutResponse `xml:"LogoutResponse,omitempty" json:"LogoutResponse,omitempty" yaml:"LogoutResponse,omitempty"`
}

// Operation wrapper for UpdateInkooporderRegel.
// OperationUpdateInkooporderRegelSoapIn was auto-generated from
// WSDL.
type OperationUpdateInkooporderRegelSoapIn struct {
	UpdateInkooporderRegel *UpdateInkooporderRegel `xml:"UpdateInkooporderRegel,omitempty" json:"UpdateInkooporderRegel,omitempty" yaml:"UpdateInkooporderRegel,omitempty"`
}

// Operation wrapper for UpdateInkooporderRegel.
// OperationUpdateInkooporderRegelSoapOut was auto-generated from
// WSDL.
type OperationUpdateInkooporderRegelSoapOut struct {
	UpdateInkooporderRegelResponse *UpdateInkooporderRegelResponse `xml:"UpdateInkooporderRegelResponse,omitempty" json:"UpdateInkooporderRegelResponse,omitempty" yaml:"UpdateInkooporderRegelResponse,omitempty"`
}

// Operation wrapper for UpdateJournaalpost.
// OperationUpdateJournaalpostSoapIn was auto-generated from WSDL.
type OperationUpdateJournaalpostSoapIn struct {
	UpdateJournaalpost *UpdateJournaalpost `xml:"UpdateJournaalpost,omitempty" json:"UpdateJournaalpost,omitempty" yaml:"UpdateJournaalpost,omitempty"`
}

// Operation wrapper for UpdateJournaalpost.
// OperationUpdateJournaalpostSoapOut was auto-generated from WSDL.
type OperationUpdateJournaalpostSoapOut struct {
	UpdateJournaalpostResponse *UpdateJournaalpostResponse `xml:"UpdateJournaalpostResponse,omitempty" json:"UpdateJournaalpostResponse,omitempty" yaml:"UpdateJournaalpostResponse,omitempty"`
}

// Operation wrapper for UpdateStamtabelRecord.
// OperationUpdateStamtabelRecordSoapIn was auto-generated from
// WSDL.
type OperationUpdateStamtabelRecordSoapIn struct {
	UpdateStamtabelRecord *UpdateStamtabelRecord `xml:"UpdateStamtabelRecord,omitempty" json:"UpdateStamtabelRecord,omitempty" yaml:"UpdateStamtabelRecord,omitempty"`
}

// Operation wrapper for UpdateStamtabelRecord.
// OperationUpdateStamtabelRecordSoapOut was auto-generated from
// WSDL.
type OperationUpdateStamtabelRecordSoapOut struct {
	UpdateStamtabelRecordResponse *UpdateStamtabelRecordResponse `xml:"UpdateStamtabelRecordResponse,omitempty" json:"UpdateStamtabelRecordResponse,omitempty" yaml:"UpdateStamtabelRecordResponse,omitempty"`
}

// Operation wrapper for UpdateVerkoopContractRegel.
// OperationUpdateVerkoopContractRegelSoapIn was auto-generated
// from WSDL.
type OperationUpdateVerkoopContractRegelSoapIn struct {
	UpdateVerkoopContractRegel *UpdateVerkoopContractRegel `xml:"UpdateVerkoopContractRegel,omitempty" json:"UpdateVerkoopContractRegel,omitempty" yaml:"UpdateVerkoopContractRegel,omitempty"`
}

// Operation wrapper for UpdateVerkoopContractRegel.
// OperationUpdateVerkoopContractRegelSoapOut was auto-generated
// from WSDL.
type OperationUpdateVerkoopContractRegelSoapOut struct {
	UpdateVerkoopContractRegelResponse *UpdateVerkoopContractRegelResponse `xml:"UpdateVerkoopContractRegelResponse,omitempty" json:"UpdateVerkoopContractRegelResponse,omitempty" yaml:"UpdateVerkoopContractRegelResponse,omitempty"`
}

// Operation wrapper for UpdateVerkooporderPickBonGepakt.
// OperationUpdateVerkooporderPickBonGepaktSoapIn was auto-generated
// from WSDL.
type OperationUpdateVerkooporderPickBonGepaktSoapIn struct {
	UpdateVerkooporderPickBonGepakt *UpdateVerkooporderPickBonGepakt `xml:"UpdateVerkooporderPickBonGepakt,omitempty" json:"UpdateVerkooporderPickBonGepakt,omitempty" yaml:"UpdateVerkooporderPickBonGepakt,omitempty"`
}

// Operation wrapper for UpdateVerkooporderPickBonGepakt.
// OperationUpdateVerkooporderPickBonGepaktSoapOut was auto-generated
// from WSDL.
type OperationUpdateVerkooporderPickBonGepaktSoapOut struct {
	UpdateVerkooporderPickBonGepaktResponse *UpdateVerkooporderPickBonGepaktResponse `xml:"UpdateVerkooporderPickBonGepaktResponse,omitempty" json:"UpdateVerkooporderPickBonGepaktResponse,omitempty" yaml:"UpdateVerkooporderPickBonGepaktResponse,omitempty"`
}

// Operation wrapper for UpdateVerkooporderPickbonGereed.
// OperationUpdateVerkooporderPickbonGereedSoapIn was auto-generated
// from WSDL.
type OperationUpdateVerkooporderPickbonGereedSoapIn struct {
	UpdateVerkooporderPickbonGereed *UpdateVerkooporderPickbonGereed `xml:"UpdateVerkooporderPickbonGereed,omitempty" json:"UpdateVerkooporderPickbonGereed,omitempty" yaml:"UpdateVerkooporderPickbonGereed,omitempty"`
}

// Operation wrapper for UpdateVerkooporderPickbonGereed.
// OperationUpdateVerkooporderPickbonGereedSoapOut was auto-generated
// from WSDL.
type OperationUpdateVerkooporderPickbonGereedSoapOut struct {
	UpdateVerkooporderPickbonGereedResponse *UpdateVerkooporderPickbonGereedResponse `xml:"UpdateVerkooporderPickbonGereedResponse,omitempty" json:"UpdateVerkooporderPickbonGereedResponse,omitempty" yaml:"UpdateVerkooporderPickbonGereedResponse,omitempty"`
}

// Operation wrapper for UpdateVerkooporderRegel.
// OperationUpdateVerkooporderRegelSoapIn was auto-generated from
// WSDL.
type OperationUpdateVerkooporderRegelSoapIn struct {
	UpdateVerkooporderRegel *UpdateVerkooporderRegel `xml:"UpdateVerkooporderRegel,omitempty" json:"UpdateVerkooporderRegel,omitempty" yaml:"UpdateVerkooporderRegel,omitempty"`
}

// Operation wrapper for UpdateVerkooporderRegel.
// OperationUpdateVerkooporderRegelSoapOut was auto-generated from
// WSDL.
type OperationUpdateVerkooporderRegelSoapOut struct {
	UpdateVerkooporderRegelResponse *UpdateVerkooporderRegelResponse `xml:"UpdateVerkooporderRegelResponse,omitempty" json:"UpdateVerkooporderRegelResponse,omitempty" yaml:"UpdateVerkooporderRegelResponse,omitempty"`
}

// ws1_xmlSoap implements the Ws1_xmlSoap interface.
type ws1_xmlSoap struct {
	cli *soap.Client
}

// CheckConnection was auto-generated from WSDL.
func (p *ws1_xmlSoap) CheckConnection(CheckConnection *CheckConnection) (*CheckConnectionResponse, error) {
	α := struct {
		OperationCheckConnectionSoapIn `xml:"tns:CheckConnection"`
	}{
		OperationCheckConnectionSoapIn{
			CheckConnection,
		},
	}

	γ := struct {
		OperationCheckConnectionSoapOut `xml:"CheckConnectionResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/CheckConnection", α, &γ); err != nil {
		return nil, err
	}
	return γ.CheckConnectionResponse, nil
}

// CreateGoederenontvangst was auto-generated from WSDL.
func (p *ws1_xmlSoap) CreateGoederenontvangst(CreateGoederenontvangst *CreateGoederenontvangst) (*CreateGoederenontvangstResponse, error) {
	α := struct {
		OperationCreateGoederenontvangstSoapIn `xml:"tns:CreateGoederenontvangst"`
	}{
		OperationCreateGoederenontvangstSoapIn{
			CreateGoederenontvangst,
		},
	}

	γ := struct {
		OperationCreateGoederenontvangstSoapOut `xml:"CreateGoederenontvangstResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/CreateGoederenontvangst", α, &γ); err != nil {
		return nil, err
	}
	return γ.CreateGoederenontvangstResponse, nil
}

// CreateInkoopOrder was auto-generated from WSDL.
func (p *ws1_xmlSoap) CreateInkoopOrder(CreateInkoopOrder *CreateInkoopOrder) (*CreateInkoopOrderResponse, error) {
	α := struct {
		OperationCreateInkoopOrderSoapIn `xml:"tns:CreateInkoopOrder"`
	}{
		OperationCreateInkoopOrderSoapIn{
			CreateInkoopOrder,
		},
	}

	γ := struct {
		OperationCreateInkoopOrderSoapOut `xml:"CreateInkoopOrderResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/CreateInkoopOrder", α, &γ); err != nil {
		return nil, err
	}
	return γ.CreateInkoopOrderResponse, nil
}

// CreateInkoopfactuur was auto-generated from WSDL.
func (p *ws1_xmlSoap) CreateInkoopfactuur(CreateInkoopfactuur *CreateInkoopfactuur) (*CreateInkoopfactuurResponse, error) {
	α := struct {
		OperationCreateInkoopfactuurSoapIn `xml:"tns:CreateInkoopfactuur"`
	}{
		OperationCreateInkoopfactuurSoapIn{
			CreateInkoopfactuur,
		},
	}

	γ := struct {
		OperationCreateInkoopfactuurSoapOut `xml:"CreateInkoopfactuurResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/CreateInkoopfactuur", α, &γ); err != nil {
		return nil, err
	}
	return γ.CreateInkoopfactuurResponse, nil
}

// CreateInkooporderRegel was auto-generated from WSDL.
func (p *ws1_xmlSoap) CreateInkooporderRegel(CreateInkooporderRegel *CreateInkooporderRegel) (*CreateInkooporderRegelResponse, error) {
	α := struct {
		OperationCreateInkooporderRegelSoapIn `xml:"tns:CreateInkooporderRegel"`
	}{
		OperationCreateInkooporderRegelSoapIn{
			CreateInkooporderRegel,
		},
	}

	γ := struct {
		OperationCreateInkooporderRegelSoapOut `xml:"CreateInkooporderRegelResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/CreateInkooporderRegel", α, &γ); err != nil {
		return nil, err
	}
	return γ.CreateInkooporderRegelResponse, nil
}

// CreateJournaalpost was auto-generated from WSDL.
func (p *ws1_xmlSoap) CreateJournaalpost(CreateJournaalpost *CreateJournaalpost) (*CreateJournaalpostResponse, error) {
	α := struct {
		OperationCreateJournaalpostSoapIn `xml:"tns:CreateJournaalpost"`
	}{
		OperationCreateJournaalpostSoapIn{
			CreateJournaalpost,
		},
	}

	γ := struct {
		OperationCreateJournaalpostSoapOut `xml:"CreateJournaalpostResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/CreateJournaalpost", α, &γ); err != nil {
		return nil, err
	}
	return γ.CreateJournaalpostResponse, nil
}

// CreateSpitsfactuur was auto-generated from WSDL.
func (p *ws1_xmlSoap) CreateSpitsfactuur(CreateSpitsfactuur *CreateSpitsfactuur) (*CreateSpitsfactuurResponse, error) {
	α := struct {
		OperationCreateSpitsfactuurSoapIn `xml:"tns:CreateSpitsfactuur"`
	}{
		OperationCreateSpitsfactuurSoapIn{
			CreateSpitsfactuur,
		},
	}

	γ := struct {
		OperationCreateSpitsfactuurSoapOut `xml:"CreateSpitsfactuurResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/CreateSpitsfactuur", α, &γ); err != nil {
		return nil, err
	}
	return γ.CreateSpitsfactuurResponse, nil
}

// CreateStamTabelRecord was auto-generated from WSDL.
func (p *ws1_xmlSoap) CreateStamTabelRecord(CreateStamTabelRecord *CreateStamTabelRecord) (*CreateStamTabelRecordResponse, error) {
	α := struct {
		OperationCreateStamTabelRecordSoapIn `xml:"tns:CreateStamTabelRecord"`
	}{
		OperationCreateStamTabelRecordSoapIn{
			CreateStamTabelRecord,
		},
	}

	γ := struct {
		OperationCreateStamTabelRecordSoapOut `xml:"CreateStamTabelRecordResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/CreateStamTabelRecord", α, &γ); err != nil {
		return nil, err
	}
	return γ.CreateStamTabelRecordResponse, nil
}

// CreateVerkoopContract was auto-generated from WSDL.
func (p *ws1_xmlSoap) CreateVerkoopContract(CreateVerkoopContract *CreateVerkoopContract) (*CreateVerkoopContractResponse, error) {
	α := struct {
		OperationCreateVerkoopContractSoapIn `xml:"tns:CreateVerkoopContract"`
	}{
		OperationCreateVerkoopContractSoapIn{
			CreateVerkoopContract,
		},
	}

	γ := struct {
		OperationCreateVerkoopContractSoapOut `xml:"CreateVerkoopContractResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/CreateVerkoopContract", α, &γ); err != nil {
		return nil, err
	}
	return γ.CreateVerkoopContractResponse, nil
}

// CreateVerkoopContractRegel was auto-generated from WSDL.
func (p *ws1_xmlSoap) CreateVerkoopContractRegel(CreateVerkoopContractRegel *CreateVerkoopContractRegel) (*CreateVerkoopContractRegelResponse, error) {
	α := struct {
		OperationCreateVerkoopContractRegelSoapIn `xml:"tns:CreateVerkoopContractRegel"`
	}{
		OperationCreateVerkoopContractRegelSoapIn{
			CreateVerkoopContractRegel,
		},
	}

	γ := struct {
		OperationCreateVerkoopContractRegelSoapOut `xml:"CreateVerkoopContractRegelResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/CreateVerkoopContractRegel", α, &γ); err != nil {
		return nil, err
	}
	return γ.CreateVerkoopContractRegelResponse, nil
}

// CreateVerkoopOrder was auto-generated from WSDL.
func (p *ws1_xmlSoap) CreateVerkoopOrder(CreateVerkoopOrder *CreateVerkoopOrder) (*CreateVerkoopOrderResponse, error) {
	α := struct {
		OperationCreateVerkoopOrderSoapIn `xml:"tns:CreateVerkoopOrder"`
	}{
		OperationCreateVerkoopOrderSoapIn{
			CreateVerkoopOrder,
		},
	}

	γ := struct {
		OperationCreateVerkoopOrderSoapOut `xml:"CreateVerkoopOrderResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/CreateVerkoopOrder", α, &γ); err != nil {
		return nil, err
	}
	return γ.CreateVerkoopOrderResponse, nil
}

// CreateVerkooporderPickbon was auto-generated from WSDL.
func (p *ws1_xmlSoap) CreateVerkooporderPickbon(CreateVerkooporderPickbon *CreateVerkooporderPickbon) (*CreateVerkooporderPickbonResponse, error) {
	α := struct {
		OperationCreateVerkooporderPickbonSoapIn `xml:"tns:CreateVerkooporderPickbon"`
	}{
		OperationCreateVerkooporderPickbonSoapIn{
			CreateVerkooporderPickbon,
		},
	}

	γ := struct {
		OperationCreateVerkooporderPickbonSoapOut `xml:"CreateVerkooporderPickbonResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/CreateVerkooporderPickbon", α, &γ); err != nil {
		return nil, err
	}
	return γ.CreateVerkooporderPickbonResponse, nil
}

// CreateVerkooporderRegel was auto-generated from WSDL.
func (p *ws1_xmlSoap) CreateVerkooporderRegel(CreateVerkooporderRegel *CreateVerkooporderRegel) (*CreateVerkooporderRegelResponse, error) {
	α := struct {
		OperationCreateVerkooporderRegelSoapIn `xml:"tns:CreateVerkooporderRegel"`
	}{
		OperationCreateVerkooporderRegelSoapIn{
			CreateVerkooporderRegel,
		},
	}

	γ := struct {
		OperationCreateVerkooporderRegelSoapOut `xml:"CreateVerkooporderRegelResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/CreateVerkooporderRegel", α, &γ); err != nil {
		return nil, err
	}
	return γ.CreateVerkooporderRegelResponse, nil
}

// DeleteInkooporder was auto-generated from WSDL.
func (p *ws1_xmlSoap) DeleteInkooporder(DeleteInkooporder *DeleteInkooporder) (*DeleteInkooporderResponse, error) {
	α := struct {
		OperationDeleteInkooporderSoapIn `xml:"tns:DeleteInkooporder"`
	}{
		OperationDeleteInkooporderSoapIn{
			DeleteInkooporder,
		},
	}

	γ := struct {
		OperationDeleteInkooporderSoapOut `xml:"DeleteInkooporderResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/DeleteInkooporder", α, &γ); err != nil {
		return nil, err
	}
	return γ.DeleteInkooporderResponse, nil
}

// DeleteInkooporderRegel was auto-generated from WSDL.
func (p *ws1_xmlSoap) DeleteInkooporderRegel(DeleteInkooporderRegel *DeleteInkooporderRegel) (*DeleteInkooporderRegelResponse, error) {
	α := struct {
		OperationDeleteInkooporderRegelSoapIn `xml:"tns:DeleteInkooporderRegel"`
	}{
		OperationDeleteInkooporderRegelSoapIn{
			DeleteInkooporderRegel,
		},
	}

	γ := struct {
		OperationDeleteInkooporderRegelSoapOut `xml:"DeleteInkooporderRegelResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/DeleteInkooporderRegel", α, &γ); err != nil {
		return nil, err
	}
	return γ.DeleteInkooporderRegelResponse, nil
}

// DeleteJournaalpost was auto-generated from WSDL.
func (p *ws1_xmlSoap) DeleteJournaalpost(DeleteJournaalpost *DeleteJournaalpost) (*DeleteJournaalpostResponse, error) {
	α := struct {
		OperationDeleteJournaalpostSoapIn `xml:"tns:DeleteJournaalpost"`
	}{
		OperationDeleteJournaalpostSoapIn{
			DeleteJournaalpost,
		},
	}

	γ := struct {
		OperationDeleteJournaalpostSoapOut `xml:"DeleteJournaalpostResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/DeleteJournaalpost", α, &γ); err != nil {
		return nil, err
	}
	return γ.DeleteJournaalpostResponse, nil
}

// DeleteStamtabelRecord was auto-generated from WSDL.
func (p *ws1_xmlSoap) DeleteStamtabelRecord(DeleteStamtabelRecord *DeleteStamtabelRecord) (*DeleteStamtabelRecordResponse, error) {
	α := struct {
		OperationDeleteStamtabelRecordSoapIn `xml:"tns:DeleteStamtabelRecord"`
	}{
		OperationDeleteStamtabelRecordSoapIn{
			DeleteStamtabelRecord,
		},
	}

	γ := struct {
		OperationDeleteStamtabelRecordSoapOut `xml:"DeleteStamtabelRecordResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/DeleteStamtabelRecord", α, &γ); err != nil {
		return nil, err
	}
	return γ.DeleteStamtabelRecordResponse, nil
}

// DeleteVerkoopContract was auto-generated from WSDL.
func (p *ws1_xmlSoap) DeleteVerkoopContract(DeleteVerkoopContract *DeleteVerkoopContract) (*DeleteVerkoopContractResponse, error) {
	α := struct {
		OperationDeleteVerkoopContractSoapIn `xml:"tns:DeleteVerkoopContract"`
	}{
		OperationDeleteVerkoopContractSoapIn{
			DeleteVerkoopContract,
		},
	}

	γ := struct {
		OperationDeleteVerkoopContractSoapOut `xml:"DeleteVerkoopContractResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/DeleteVerkoopContract", α, &γ); err != nil {
		return nil, err
	}
	return γ.DeleteVerkoopContractResponse, nil
}

// DeleteVerkoopContractRegel was auto-generated from WSDL.
func (p *ws1_xmlSoap) DeleteVerkoopContractRegel(DeleteVerkoopContractRegel *DeleteVerkoopContractRegel) (*DeleteVerkoopContractRegelResponse, error) {
	α := struct {
		OperationDeleteVerkoopContractRegelSoapIn `xml:"tns:DeleteVerkoopContractRegel"`
	}{
		OperationDeleteVerkoopContractRegelSoapIn{
			DeleteVerkoopContractRegel,
		},
	}

	γ := struct {
		OperationDeleteVerkoopContractRegelSoapOut `xml:"DeleteVerkoopContractRegelResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/DeleteVerkoopContractRegel", α, &γ); err != nil {
		return nil, err
	}
	return γ.DeleteVerkoopContractRegelResponse, nil
}

// DeleteVerkooporder was auto-generated from WSDL.
func (p *ws1_xmlSoap) DeleteVerkooporder(DeleteVerkooporder *DeleteVerkooporder) (*DeleteVerkooporderResponse, error) {
	α := struct {
		OperationDeleteVerkooporderSoapIn `xml:"tns:DeleteVerkooporder"`
	}{
		OperationDeleteVerkooporderSoapIn{
			DeleteVerkooporder,
		},
	}

	γ := struct {
		OperationDeleteVerkooporderSoapOut `xml:"DeleteVerkooporderResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/DeleteVerkooporder", α, &γ); err != nil {
		return nil, err
	}
	return γ.DeleteVerkooporderResponse, nil
}

// DeleteVerkooporderRegel was auto-generated from WSDL.
func (p *ws1_xmlSoap) DeleteVerkooporderRegel(DeleteVerkooporderRegel *DeleteVerkooporderRegel) (*DeleteVerkooporderRegelResponse, error) {
	α := struct {
		OperationDeleteVerkooporderRegelSoapIn `xml:"tns:DeleteVerkooporderRegel"`
	}{
		OperationDeleteVerkooporderRegelSoapIn{
			DeleteVerkooporderRegel,
		},
	}

	γ := struct {
		OperationDeleteVerkooporderRegelSoapOut `xml:"DeleteVerkooporderRegelResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/DeleteVerkooporderRegel", α, &γ); err != nil {
		return nil, err
	}
	return γ.DeleteVerkooporderRegelResponse, nil
}

// GetAdmInfo was auto-generated from WSDL.
func (p *ws1_xmlSoap) GetAdmInfo(GetAdmInfo *GetAdmInfo) (*GetAdmInfoResponse, error) {
	α := struct {
		OperationGetAdmInfoSoapIn `xml:"tns:GetAdmInfo"`
	}{
		OperationGetAdmInfoSoapIn{
			GetAdmInfo,
		},
	}

	γ := struct {
		OperationGetAdmInfoSoapOut `xml:"GetAdmInfoResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/GetAdmInfo", α, &γ); err != nil {
		return nil, err
	}
	return γ.GetAdmInfoResponse, nil
}

// GetLaatsteBoekingPeriode was auto-generated from WSDL.
func (p *ws1_xmlSoap) GetLaatsteBoekingPeriode(GetLaatsteBoekingPeriode *GetLaatsteBoekingPeriode) (*GetLaatsteBoekingPeriodeResponse, error) {
	α := struct {
		OperationGetLaatsteBoekingPeriodeSoapIn `xml:"tns:GetLaatsteBoekingPeriode"`
	}{
		OperationGetLaatsteBoekingPeriodeSoapIn{
			GetLaatsteBoekingPeriode,
		},
	}

	γ := struct {
		OperationGetLaatsteBoekingPeriodeSoapOut `xml:"GetLaatsteBoekingPeriodeResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/GetLaatsteBoekingPeriode", α, &γ); err != nil {
		return nil, err
	}
	return γ.GetLaatsteBoekingPeriodeResponse, nil
}

// GetPredefindQuery was auto-generated from WSDL.
func (p *ws1_xmlSoap) GetPredefindQuery(GetPredefindQuery *GetPredefindQuery) (*GetPredefindQueryResponse, error) {
	α := struct {
		OperationGetPredefindQuerySoapIn `xml:"tns:GetPredefindQuery"`
	}{
		OperationGetPredefindQuerySoapIn{
			GetPredefindQuery,
		},
	}

	γ := struct {
		OperationGetPredefindQuerySoapOut `xml:"GetPredefindQueryResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/GetPredefindQuery", α, &γ); err != nil {
		return nil, err
	}
	return γ.GetPredefindQueryResponse, nil
}

// GetStamtabelRecords was auto-generated from WSDL.
func (p *ws1_xmlSoap) GetStamtabelRecords(GetStamtabelRecords *GetStamtabelRecords, data interface{}) (*GetStamtabelRecordsResponse, error) {
	α := struct {
		OperationGetStamtabelRecordsSoapIn `xml:"tns:GetStamtabelRecords"`
	}{
		OperationGetStamtabelRecordsSoapIn{
			GetStamtabelRecords,
		},
	}

	γ := struct {
		OperationGetStamtabelRecordsSoapOut `xml:"GetStamtabelRecordsResponse"`
	}{}
	γ.GetStamtabelRecordsResponse = &GetStamtabelRecordsResponse{
		Records: GetStamtabelRecordsResponseRecords{
			NewDataSet: NewDataSet{
				Data: data,
			},
		},
	}
	// log.Fatal(reflect.TypeOf(γ.GetStamtabelRecordsResponse.Records))
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/GetStamtabelRecords", α, &γ); err != nil {
		return nil, err
	}
	return γ.GetStamtabelRecordsResponse, nil
}

// GetTimeStamp was auto-generated from WSDL.
func (p *ws1_xmlSoap) GetTimeStamp(GetTimeStamp *GetTimeStamp) (*GetTimeStampResponse, error) {
	α := struct {
		OperationGetTimeStampSoapIn `xml:"tns:GetTimeStamp"`
	}{
		OperationGetTimeStampSoapIn{
			GetTimeStamp,
		},
	}

	γ := struct {
		OperationGetTimeStampSoapOut `xml:"GetTimeStampResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/GetTimeStamp", α, &γ); err != nil {
		return nil, err
	}
	return γ.GetTimeStampResponse, nil
}

// GetiMUISVersion was auto-generated from WSDL.
func (p *ws1_xmlSoap) GetiMUISVersion(GetiMUISVersion *GetiMUISVersion) (*GetiMUISVersionResponse, error) {
	α := struct {
		OperationGetiMUISVersionSoapIn `xml:"tns:GetiMUISVersion"`
	}{
		OperationGetiMUISVersionSoapIn{
			GetiMUISVersion,
		},
	}

	γ := struct {
		OperationGetiMUISVersionSoapOut `xml:"GetiMUISVersionResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/GetiMUISVersion", α, &γ); err != nil {
		return nil, err
	}
	return γ.GetiMUISVersionResponse, nil
}

// KeepSession was auto-generated from WSDL.
func (p *ws1_xmlSoap) KeepSession(KeepSession *KeepSession) (*KeepSessionResponse, error) {
	α := struct {
		OperationKeepSessionSoapIn `xml:"tns:KeepSession"`
	}{
		OperationKeepSessionSoapIn{
			KeepSession,
		},
	}

	γ := struct {
		OperationKeepSessionSoapOut `xml:"KeepSessionResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/KeepSession", α, &γ); err != nil {
		return nil, err
	}
	return γ.KeepSessionResponse, nil
}

// Login was auto-generated from WSDL.
func (p *ws1_xmlSoap) Login(Login *Login) (*LoginResponse, error) {
	α := struct {
		OperationLoginSoapIn `xml:"tns:Login"`
	}{
		OperationLoginSoapIn{
			Login,
		},
	}

	γ := struct {
		OperationLoginSoapOut `xml:"LoginResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/Login", α, &γ); err != nil {
		return nil, err
	}
	return γ.LoginResponse, nil
}

// Logout was auto-generated from WSDL.
func (p *ws1_xmlSoap) Logout(Logout *Logout) (*LogoutResponse, error) {
	α := struct {
		OperationLogoutSoapIn `xml:"tns:Logout"`
	}{
		OperationLogoutSoapIn{
			Logout,
		},
	}

	γ := struct {
		OperationLogoutSoapOut `xml:"LogoutResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/Logout", α, &γ); err != nil {
		return nil, err
	}
	return γ.LogoutResponse, nil
}

// UpdateInkooporderRegel was auto-generated from WSDL.
func (p *ws1_xmlSoap) UpdateInkooporderRegel(UpdateInkooporderRegel *UpdateInkooporderRegel) (*UpdateInkooporderRegelResponse, error) {
	α := struct {
		OperationUpdateInkooporderRegelSoapIn `xml:"tns:UpdateInkooporderRegel"`
	}{
		OperationUpdateInkooporderRegelSoapIn{
			UpdateInkooporderRegel,
		},
	}

	γ := struct {
		OperationUpdateInkooporderRegelSoapOut `xml:"UpdateInkooporderRegelResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/UpdateInkooporderRegel", α, &γ); err != nil {
		return nil, err
	}
	return γ.UpdateInkooporderRegelResponse, nil
}

// UpdateJournaalpost was auto-generated from WSDL.
func (p *ws1_xmlSoap) UpdateJournaalpost(UpdateJournaalpost *UpdateJournaalpost) (*UpdateJournaalpostResponse, error) {
	α := struct {
		OperationUpdateJournaalpostSoapIn `xml:"tns:UpdateJournaalpost"`
	}{
		OperationUpdateJournaalpostSoapIn{
			UpdateJournaalpost,
		},
	}

	γ := struct {
		OperationUpdateJournaalpostSoapOut `xml:"UpdateJournaalpostResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/UpdateJournaalpost", α, &γ); err != nil {
		return nil, err
	}
	return γ.UpdateJournaalpostResponse, nil
}

// UpdateStamtabelRecord was auto-generated from WSDL.
func (p *ws1_xmlSoap) UpdateStamtabelRecord(UpdateStamtabelRecord *UpdateStamtabelRecord) (*UpdateStamtabelRecordResponse, error) {
	α := struct {
		OperationUpdateStamtabelRecordSoapIn `xml:"tns:UpdateStamtabelRecord"`
	}{
		OperationUpdateStamtabelRecordSoapIn{
			UpdateStamtabelRecord,
		},
	}

	γ := struct {
		OperationUpdateStamtabelRecordSoapOut `xml:"UpdateStamtabelRecordResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/UpdateStamtabelRecord", α, &γ); err != nil {
		return nil, err
	}
	return γ.UpdateStamtabelRecordResponse, nil
}

// UpdateVerkoopContractRegel was auto-generated from WSDL.
func (p *ws1_xmlSoap) UpdateVerkoopContractRegel(UpdateVerkoopContractRegel *UpdateVerkoopContractRegel) (*UpdateVerkoopContractRegelResponse, error) {
	α := struct {
		OperationUpdateVerkoopContractRegelSoapIn `xml:"tns:UpdateVerkoopContractRegel"`
	}{
		OperationUpdateVerkoopContractRegelSoapIn{
			UpdateVerkoopContractRegel,
		},
	}

	γ := struct {
		OperationUpdateVerkoopContractRegelSoapOut `xml:"UpdateVerkoopContractRegelResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/UpdateVerkoopContractRegel", α, &γ); err != nil {
		return nil, err
	}
	return γ.UpdateVerkoopContractRegelResponse, nil
}

// UpdateVerkooporderPickBonGepakt was auto-generated from WSDL.
func (p *ws1_xmlSoap) UpdateVerkooporderPickBonGepakt(UpdateVerkooporderPickBonGepakt *UpdateVerkooporderPickBonGepakt) (*UpdateVerkooporderPickBonGepaktResponse, error) {
	α := struct {
		OperationUpdateVerkooporderPickBonGepaktSoapIn `xml:"tns:UpdateVerkooporderPickBonGepakt"`
	}{
		OperationUpdateVerkooporderPickBonGepaktSoapIn{
			UpdateVerkooporderPickBonGepakt,
		},
	}

	γ := struct {
		OperationUpdateVerkooporderPickBonGepaktSoapOut `xml:"UpdateVerkooporderPickBonGepaktResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/UpdateVerkooporderPickBonGepakt", α, &γ); err != nil {
		return nil, err
	}
	return γ.UpdateVerkooporderPickBonGepaktResponse, nil
}

// UpdateVerkooporderPickbonGereed was auto-generated from WSDL.
func (p *ws1_xmlSoap) UpdateVerkooporderPickbonGereed(UpdateVerkooporderPickbonGereed *UpdateVerkooporderPickbonGereed) (*UpdateVerkooporderPickbonGereedResponse, error) {
	α := struct {
		OperationUpdateVerkooporderPickbonGereedSoapIn `xml:"tns:UpdateVerkooporderPickbonGereed"`
	}{
		OperationUpdateVerkooporderPickbonGereedSoapIn{
			UpdateVerkooporderPickbonGereed,
		},
	}

	γ := struct {
		OperationUpdateVerkooporderPickbonGereedSoapOut `xml:"UpdateVerkooporderPickbonGereedResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/UpdateVerkooporderPickbonGereed", α, &γ); err != nil {
		return nil, err
	}
	return γ.UpdateVerkooporderPickbonGereedResponse, nil
}

// UpdateVerkooporderRegel was auto-generated from WSDL.
func (p *ws1_xmlSoap) UpdateVerkooporderRegel(UpdateVerkooporderRegel *UpdateVerkooporderRegel) (*UpdateVerkooporderRegelResponse, error) {
	α := struct {
		OperationUpdateVerkooporderRegelSoapIn `xml:"tns:UpdateVerkooporderRegel"`
	}{
		OperationUpdateVerkooporderRegelSoapIn{
			UpdateVerkooporderRegel,
		},
	}

	γ := struct {
		OperationUpdateVerkooporderRegelSoapOut `xml:"UpdateVerkooporderRegelResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("https://cloudswitch.imuisonline.com/UpdateVerkooporderRegel", α, &γ); err != nil {
		return nil, err
	}
	return γ.UpdateVerkooporderRegelResponse, nil
}
